apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  namespace: poketools
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - env:
            - name: APP_VERSION
              value: dev
            - name: BUILD_NUMBER
              value: k8s_fb09e2677065fda1f25756897fd4539efde7476f
            - name: APP_ENV
              value: dev
            - name: IDE
              value: phpstorm
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: app.secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: database.url
            - name: MAILER_URL
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: mailer.url
          image: registry.gitlab.com/gamestuff.info/poketools/app:k8s_fb09e2677065fda1f25756897fd4539efde7476f
          name: php
          ports:
            - containerPort: 9000
              name: php-fpm
          readinessProbe:
            tcpSocket:
              port: 9000
      restartPolicy: Always
