version: "3.7"

services:
  app:
    build:
      target: app_dev
      args:
        - APP_ENV=dev
        - APP_DEBUG=1
    env_file:
      - app/.env
      - app/.env.local
    environment:
      APP_SECRET: 1
      APP_ENV: dev
      APP_VERSION: dev
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www
