version: "3.7"

services:
  app:
    image: dragoonboots/poketools/app
    build:
      context: .
      target: app
    environment:
      - APP_VERSION
      - BUILD_NUMBER
      - APP_ENV=prod
      - APP_SECRET
      - DATABASE_URL
      - SENTRY_DSN
    restart: always
    ports:
      - "80:80"
