version: "3.7"

services:
  app:
    image: dragoonboots/poketools/app
    build:
      context: .
      target: app
    environment:
      - APP_VERSION
      - BUILD_NUMBER
      - APP_ENV=prod
      - APP_SECRET
      - DATABASE_URL
      - SENTRY_DSN
    restart: always
    ports:
      - "80:80"
      
  db:
    image: dragoonboots/poketools/db
    build:
      dockerfile: Dockerfile.data
      context: docker/db
      # Allows overriding to get a blank db if needed.
      target: "${DB_TARGET:-db}"
    environment:
      - POSTGRES_USER=poketools
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=poketools
    ports:
      - "4321:5432"
