from typing import Dict


def get_maps(version_group: str) -> Dict[int, Dict[str, str]]:
    map_slugs = {
        0x00: {'location': 'pallet-town', 'area': 'whole-area'},
        0x01: {'location': 'viridian-city', 'area': 'whole-area'},
        0x02: {'location': 'pewter-city', 'area': 'whole-area'},
        0x03: {'location': 'cerulean-city', 'area': 'whole-area'},
        0x04: {'location': 'lavender-town', 'area': 'whole-area'},
        0x05: {'location': 'vermilion-city', 'area': 'whole-area'},
        0x06: {'location': 'celadon-city', 'area': 'whole-area'},
        0x07: {'location': 'fuchsia-city', 'area': 'whole-area'},
        0x08: {'location': 'cinnabar-island', 'area': 'whole-area'},
        0x09: {'location': 'indigo-plateau', 'area': 'whole-area'},
        0x0A: {'location': 'saffron-city', 'area': 'whole-area'},
        0x0C: {'location': 'kanto-route-1', 'area': 'whole-area'},
        0x0D: {'location': 'kanto-route-2', 'area': 'whole-area'},
        0x0E: {'location': 'kanto-route-3', 'area': 'whole-area'},
        0x0F: {'location': 'kanto-route-4', 'area': 'whole-area'},
        0x10: {'location': 'kanto-route-5', 'area': 'whole-area'},
        0x11: {'location': 'kanto-route-6', 'area': 'whole-area'},
        0x12: {'location': 'kanto-route-7', 'area': 'whole-area'},
        0x13: {'location': 'kanto-route-8', 'area': 'whole-area'},
        0x14: {'location': 'kanto-route-9', 'area': 'whole-area'},
        0x15: {'location': 'kanto-route-10', 'area': 'whole-area'},
        0x16: {'location': 'kanto-route-11', 'area': 'whole-area'},
        0x17: {'location': 'kanto-route-12', 'area': 'whole-area'},
        0x18: {'location': 'kanto-route-13', 'area': 'whole-area'},
        0x19: {'location': 'kanto-route-14', 'area': 'whole-area'},
        0x1A: {'location': 'kanto-route-15', 'area': 'whole-area'},
        0x1B: {'location': 'kanto-route-16', 'area': 'whole-area'},
        0x1C: {'location': 'kanto-route-17', 'area': 'whole-area'},
        0x1D: {'location': 'kanto-route-18', 'area': 'whole-area'},
        0x1E: {'location': 'kanto-route-19', 'area': 'whole-area'},
        0x1F: {'location': 'kanto-route-20', 'area': 'whole-area'},
        0x20: {'location': 'kanto-route-21', 'area': 'whole-area'},
        0x21: {'location': 'kanto-route-22', 'area': 'whole-area'},
        0x22: {'location': 'kanto-route-23', 'area': 'whole-area'},
        0x23: {'location': 'kanto-route-24', 'area': 'whole-area'},
        0x24: {'location': 'kanto-route-25', 'area': 'whole-area'},
        0x25: {'location': 'pallet-town', 'area': 'reds-house-1f'},
        0x26: {'location': 'pallet-town', 'area': 'reds-house-2f'},
        0x27: {'location': 'pallet-town', 'area': 'blues-house'},
        0x28: {'location': 'pallet-town', 'area': 'oaks-lab'},
        0x29: {'location': 'viridian-city', 'area': 'pokemon-center'},
        0x2A: {'location': 'viridian-city', 'area': 'mart'},
        0x2B: {'location': 'viridian-city', 'area': 'school'},
        0x2C: {'location': 'viridian-city', 'area': 'house-spearow'},
        0x2D: {'location': 'viridian-city', 'area': 'gym'},
        0x2E: {'location': 'digletts-cave', 'area': 'route-2'},
        0x2F: {'location': 'viridian-forest', 'area': 'north-gate'},
        0x30: {'location': 'kanto-route-2', 'area': 'house'},
        0x31: {'location': 'kanto-route-2', 'area': 'gate'},
        0x32: {'location': 'viridian-forest', 'area': 'south-gate'},
        0x33: {'location': 'viridian-forest', 'area': 'whole-area'},
        0x34: {'location': 'pewter-city', 'area': 'museum-1f'},
        0x35: {'location': 'pewter-city', 'area': 'museum-2f'},
        0x36: {'location': 'pewter-city', 'area': 'gym'},
        0x37: {'location': 'pewter-city', 'area': 'house-nidoran'},
        0x38: {'location': 'pewter-city', 'area': 'mart'},
        0x39: {'location': 'pewter-city', 'area': 'house'},
        0x3A: {'location': 'pewter-city', 'area': 'pokemon-center'},
        0x3B: {'location': 'mt-moon', 'area': '1f'},
        0x3C: {'location': 'mt-moon', 'area': 'b1f'},
        0x3D: {'location': 'mt-moon', 'area': 'b2f'},
        0x3E: {'location': 'cerulean-city', 'area': 'burgled-house'},
        0x3F: {'location': 'cerulean-city', 'area': 'house-jynx'},
        0x40: {'location': 'cerulean-city', 'area': 'pokemon-center'},
        0x41: {'location': 'cerulean-city', 'area': 'gym'},
        0x42: {'location': 'cerulean-city', 'area': 'bike-shop'},
        0x43: {'location': 'cerulean-city', 'area': 'mart'},
        0x44: {'location': 'kanto-route-4', 'area': 'pokemon-center'},
        # 0x45: {'location': 'cerulean-trashed-house-copy', 'area': 'whole-area'},
        0x46: {'location': 'kanto-route-5', 'area': 'south-gate'},
        0x47: {'location': 'kanto-underground-path-5-6', 'area': 'route-5'},
        0x48: {'location': 'kanto-route-5', 'area': 'daycare'},
        0x49: {'location': 'kanto-route-6', 'area': 'north-gate'},
        0x4A: {'location': 'kanto-underground-path-5-6', 'area': 'route-6'},
        # 0x4B: {'location': 'underground-path-route-6-copy', 'area': 'whole-area'},
        0x4C: {'location': 'kanto-route-7', 'area': 'east-gate'},
        0x4D: {'location': 'kanto-underground-path-7-8', 'area': 'route-7'},
        # 0x4E: {'location': 'underground-path-route-7-copy', 'area': 'whole-area'},
        0x4F: {'location': 'route-8-gate', 'area': 'whole-area'},
        0x50: {'location': 'kanto-underground-path-7-8', 'area': 'route-8'},
        0x51: {'location': 'kanto-route-10', 'area': 'pokemon-center'},
        0x52: {'location': 'rock-tunnel', 'area': 'b1f'},
        0x53: {'location': 'power-plant', 'area': 'whole-area'},
        0x54: {'location': 'kanto-route-11', 'area': 'east-gate-1f'},
        0x55: {'location': 'digletts-cave', 'area': 'route-11'},
        0x56: {'location': 'kanto-route-11', 'area': 'east-gate-2f'},
        0x57: {'location': 'kanto-route-12', 'area': 'gate-1f'},
        0x58: {'location': 'kanto-route-25', 'area': 'bills-house'},
        0x59: {'location': 'vermilion-city', 'area': 'pokemon-center'},
        0x5A: {'location': 'vermilion-city', 'area': 'pokemon-fan-club'},
        0x5B: {'location': 'vermilion-city', 'area': 'mart'},
        0x5C: {'location': 'vermilion-city', 'area': 'gym'},
        0x5D: {'location': 'vermilion-city', 'area': 'house-pidgey'},
        0x5E: {'location': 'ss-anne', 'area': 'dock'},
        0x5F: {'location': 'ss-anne', 'area': '1f'},
        0x60: {'location': 'ss-anne', 'area': '2f'},
        0x61: {'location': 'ss-anne', 'area': '3f'},
        0x62: {'location': 'ss-anne', 'area': 'b1f'},
        0x63: {'location': 'ss-anne', 'area': 'bow'},
        0x64: {'location': 'ss-anne', 'area': 'kitchen'},
        0x65: {'location': 'ss-anne', 'area': 'captains-room'},
        0x66: {'location': 'ss-anne', 'area': '1f-rooms'},
        0x67: {'location': 'ss-anne', 'area': '2f-rooms'},
        0x68: {'location': 'ss-anne', 'area': 'b1f-rooms'},
        # 0x69: {'location': 'unused-map-69', 'area': 'whole-area'},
        # 0x6A: {'location': 'unused-map-6a', 'area': 'whole-area'},
        # 0x6B: {'location': 'unused-map-6b', 'area': 'whole-area'},
        0x6C: {'location': 'kanto-victory-road', 'area': '1f'},
        # 0x6D: {'location': 'unused-map-6d', 'area': 'whole-area'},
        # 0x6E: {'location': 'unused-map-6e', 'area': 'whole-area'},
        # 0x6F: {'location': 'unused-map-6f', 'area': 'whole-area'},
        # 0x70: {'location': 'unused-map-70', 'area': 'whole-area'},
        0x71: {'location': 'indigo-plateau', 'area': 'lances-room'},
        # 0x72: {'location': 'unused-map-72', 'area': 'whole-area'},
        # 0x73: {'location': 'unused-map-73', 'area': 'whole-area'},
        # 0x74: {'location': 'unused-map-74', 'area': 'whole-area'},
        # 0x75: {'location': 'unused-map-75', 'area': 'whole-area'},
        0x76: {'location': 'indigo-plateau', 'area': 'hall-of-fame'},
        0x77: {'location': 'kanto-underground-path-5-6', 'area': 'underground'},
        0x78: {'location': 'indigo-plateau', 'area': 'champions-room'},
        0x79: {'location': 'kanto-underground-path-7-8', 'area': 'underground'},
        0x7A: {'location': 'celadon-city', 'area': 'department-store/1f'},
        0x7B: {'location': 'celadon-city', 'area': 'department-store/2f'},
        0x7C: {'location': 'celadon-city', 'area': 'department-store/3f'},
        0x7D: {'location': 'celadon-city', 'area': 'department-store/4f'},
        0x7E: {'location': 'celadon-city', 'area': 'department-store/roof'},
        0x7F: {'location': 'celadon-city', 'area': 'department-store/elevator'},
        0x80: {'location': 'celadon-city', 'area': 'celadon-mansion/1f'},
        0x81: {'location': 'celadon-city', 'area': 'celadon-mansion/2f'},
        0x82: {'location': 'celadon-city', 'area': 'celadon-mansion/3f'},
        0x83: {'location': 'celadon-city', 'area': 'celadon-mansion/roof'},
        0x84: {'location': 'celadon-city', 'area': 'celadon-mansion/roof-house'},
        0x85: {'location': 'celadon-city', 'area': 'pokemon-center'},
        0x86: {'location': 'celadon-city', 'area': 'gym'},
        0x87: {'location': 'celadon-city', 'area': 'game-corner'},
        0x88: {'location': 'celadon-city', 'area': 'department-store/5f'},
        0x89: {'location': 'celadon-city', 'area': 'game-corner-prize-room'},
        0x8A: {'location': 'celadon-city', 'area': 'diner'},
        0x8B: {'location': 'celadon-city', 'area': 'house-boss'},  # The game corner boss' house
        0x8C: {'location': 'celadon-city', 'area': 'hotel'},
        0x8D: {'location': 'lavender-town', 'area': 'pokemon-center'},
        0x8E: {'location': 'pokemon-tower', 'area': '1f'},
        0x8F: {'location': 'pokemon-tower', 'area': '2f'},
        0x90: {'location': 'pokemon-tower', 'area': '3f'},
        0x91: {'location': 'pokemon-tower', 'area': '4f'},
        0x92: {'location': 'pokemon-tower', 'area': '5f'},
        0x93: {'location': 'pokemon-tower', 'area': '6f'},
        0x94: {'location': 'pokemon-tower', 'area': '7f'},
        0x95: {'location': 'lavender-town', 'area': 'mr-fujis-house'},
        0x96: {'location': 'lavender-town', 'area': 'mart'},
        0x97: {'location': 'lavender-town', 'area': 'cubone-house'},
        0x98: {'location': 'fuchsia-city', 'area': 'mart'},
        0x99: {'location': 'fuchsia-city', 'area': 'bills-grandpas-house'},
        0x9A: {'location': 'fuchsia-city', 'area': 'pokemon-center'},
        0x9B: {'location': 'fuchsia-city', 'area': 'wardens-house'},
        0x9C: {'location': 'kanto-safari-zone', 'area': 'gate'},
        0x9D: {'location': 'fuchsia-city', 'area': 'gym'},
        0x9E: {'location': 'fuchsia-city', 'area': 'safari-zone-staff'},
        0x9F: {'location': 'seafoam-islands', 'area': 'b1f'},
        0xA0: {'location': 'seafoam-islands', 'area': 'b2f'},
        0xA1: {'location': 'seafoam-islands', 'area': 'b3f'},
        0xA2: {'location': 'seafoam-islands', 'area': 'b4f'},
        0xA3: {'location': 'vermilion-city', 'area': 'fishing-guru'},
        0xA4: {'location': 'fuchsia-city', 'area': 'fishing-guru'},
        0xA5: {'location': 'pokemon-mansion', 'area': '1f'},
        0xA6: {'location': 'cinnabar-island', 'area': 'gym'},
        0xA7: {'location': 'cinnabar-island', 'area': 'lab'},
        0xA8: {'location': 'cinnabar-island', 'area': 'lab-meeting-room'},
        0xA9: {'location': 'cinnabar-island', 'area': 'lab r-d-room'},
        0xAA: {'location': 'cinnabar-island', 'area': 'testing-room'},
        0xAB: {'location': 'cinnabar-island', 'area': 'pokemon-center'},
        0xAC: {'location': 'cinnabar-island', 'area': 'mart'},
        # 0xAD: {'location': 'cinnabar-mart-copy', 'area': 'whole-area'},
        0xAE: {'location': 'indigo-plateau', 'area': 'lobby'},
        0xAF: {'location': 'saffron-city', 'area': 'copycats-house-1f'},
        0xB0: {'location': 'saffron-city', 'area': 'copycats-house-2f'},
        0xB1: {'location': 'saffron-city', 'area': 'fighting-dojo'},
        0xB2: {'location': 'saffron-city', 'area': 'gym'},
        0xB3: {'location': 'saffron-city', 'area': 'house-pidgey'},
        0xB4: {'location': 'saffron-mart', 'area': 'whole-area'},
        0xB5: {'location': 'silph-co', 'area': '1f'},
        0xB6: {'location': 'saffron-city', 'area': 'pokemon-center'},
        0xB7: {'location': 'saffron-city', 'area': 'mr-psychics-house'},
        0xB8: {'location': 'kanto-route-15', 'area': 'west-gate-1f'},
        0xB9: {'location': 'kanto-route-15', 'area': 'west-gate-2f'},
        0xBA: {'location': 'kanto-route-16', 'area': 'gate-1f'},
        0xBB: {'location': 'kanto-route-16', 'area': 'gate-2f'},
        0xBC: {'location': 'kanto-route-16', 'area': 'recluses-house'},
        0xBD: {'location': 'kanto-route-12', 'area': 'fishing-guru'},
        0xBE: {'location': 'kanto-route-18', 'area': 'gate-1f'},
        0xBF: {'location': 'kanto-route-18', 'area': 'gate-2f'},
        0xC0: {'location': 'seafoam-islands', 'area': '1f'},
        0xC1: {'location': 'route-23', 'area': 'entrance'},
        0xC2: {'location': 'kanto-victory-road', 'area': '2f'},
        0xC3: {'location': 'route-12', 'area': 'gate-2f'},
        0xC4: {'location': 'vermilion-city', 'area': 'house-girl'},
        0xC5: {'location': 'digletts-cave', 'area': 'underground'},
        0xC6: {'location': 'kanto-victory-road', 'area': '3f'},
        0xC7: {'location': 'rocket-hideout', 'area': 'b1f'},
        0xC8: {'location': 'rocket-hideout', 'area': 'b2f'},
        0xC9: {'location': 'rocket-hideout', 'area': 'b3f'},
        0xCA: {'location': 'rocket-hideout', 'area': 'b4f'},
        0xCB: {'location': 'rocket-hideout', 'area': 'elevator'},
        # 0xCC: {'location': 'unused-map-cc', 'area': 'whole-area'},
        # 0xCD: {'location': 'unused-map-cd', 'area': 'whole-area'},
        # 0xCE: {'location': 'unused-map-ce', 'area': 'whole-area'},
        0xCF: {'location': 'silph-co', 'area': '2f'},
        0xD0: {'location': 'silph-co', 'area': '3f'},
        0xD1: {'location': 'silph-co', 'area': '4f'},
        0xD2: {'location': 'silph-co', 'area': '5f'},
        0xD3: {'location': 'silph-co', 'area': '6f'},
        0xD4: {'location': 'silph-co', 'area': '7f'},
        0xD5: {'location': 'silph-co', 'area': '8f'},
        0xD6: {'location': 'pokemon-mansion', 'area': '2f'},
        0xD7: {'location': 'pokemon-mansion', 'area': '3f'},
        0xD8: {'location': 'pokemon-mansion', 'area': 'b1f'},
        0xD9: {'location': 'kanto-safari-zone', 'area': 'area-1-east'},
        0xDA: {'location': 'kanto-safari-zone', 'area': 'area-2-north'},
        0xDB: {'location': 'kanto-safari-zone', 'area': 'area-3-west'},
        0xDC: {'location': 'kanto-safari-zone', 'area': 'middle'},
        0xDD: {'location': 'kanto-safari-zone', 'area': 'middle-rest-house'},
        0xDE: {'location': 'kanto-safari-zone', 'area': 'area-3-west-secret-house'},
        0xDF: {'location': 'kanto-safari-zone', 'area': 'area-3-west-rest-house'},
        0xE0: {'location': 'kanto-safari-zone', 'area': 'area-1-east-rest-house'},
        0xE1: {'location': 'kanto-safari-zone', 'area': 'area-2-north-rest-house'},
        0xE2: {'location': 'cerulean-cave', 'area': '2f'},
        0xE3: {'location': 'cerulean-cave', 'area': 'b1f'},
        0xE4: {'location': 'cerulean-cave', 'area': '1f'},
        0xE5: {'location': 'lavender-town', 'area': 'name-raters-house'},
        0xE6: {'location': 'cerulean-city', 'area': 'badge-mans-house'},
        # 0xE7: {'location': 'unused-map-e7', 'area': 'whole-area'},
        0xE8: {'location': 'rock-tunnel', 'area': 'b2f'},
        0xE9: {'location': 'silph-co', 'area': '9f'},
        0xEA: {'location': 'silph-co', 'area': '10f'},
        0xEB: {'location': 'silph-co', 'area': '11f'},
        0xEC: {'location': 'silph-co', 'area': 'elevator'},
        # 0xED: {'location': 'unused-map-ed', 'area': 'whole-area'},
        # 0xEE: {'location': 'unused-map-ee', 'area': 'whole-area'},
        # 0xEF: {'location': 'trade-center', 'area': 'whole-area'},
        # 0xF0: {'location': 'colosseum', 'area': 'whole-area'},
        # 0xF1: {'location': 'unused-map-f1', 'area': 'whole-area'},
        # 0xF2: {'location': 'unused-map-f2', 'area': 'whole-area'},
        # 0xF3: {'location': 'unused-map-f3', 'area': 'whole-area'},
        # 0xF4: {'location': 'unused-map-f4', 'area': 'whole-area'},
        0xF5: {'location': 'indigo-plateau', 'area': 'loreleis-room'},
        0xF6: {'location': 'indigo-plateau', 'area': 'brunos-room'},
        0xF7: {'location': 'indigo-plateau', 'area': 'agathas-room'},
    }

    return map_slugs
