services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true
  
  test.commonmark.converter:
    parent: League\CommonMark\CommonMarkConverter
    public: true
    autowire: false
    autoconfigure: false
  
  test.yaml.parser:
    class: Symfony\Component\Yaml\Parser
    
  test.serializer.encoder.json:
    class: Symfony\Component\Serializer\Encoder\JsonEncoder
