imports:
  - resource: services/doctrine_extensions.yaml
  - resource: services/menus.yaml

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
  locale: 'en'
  app_name: Pokètools
  default_version: ultra-sun
  asset_path: '%kernel.project_dir%/assets'
  data_path: '%kernel.project_dir%/resources/data'
  commonmark_config:
    html_input: strip
    allow_unsafe_links: false

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false       # Allows optimizing the container by removing unused services; this also means
    # fetching services directly from the container via $container->get() won't work.
    # The best practice is to be explicit about your dependencies anyway.
  
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: '../src/*'
    exclude: '../src/{Menu,Entity,Migrations,Tests}'
  
  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  App\Controller\:
    resource: '../src/Controller'
    public: true
    tags: ['controller.service_arguments']
  
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
  App\A2B\Drivers\Destination\DbalDestinationDriver:
    arguments:
      - '@a2b.league.uri.parser'
      - '@doctrine.dbal.connection_factory'
  App\A2B\Drivers\Source\FileSourceDriver:
    arguments:
      - '@a2b.league.uri.parser'
  App\A2B\Drivers\Destination\FileDestinationDriver:
    arguments:
      - '@a2b.league.uri.parser'
  
  # Current version, only available after controller resolution
  app.active_version:
    class: App\Entity\Version
    public: true
    synthetic: true
  
  App\Command\DataCleanYamlCommand:
    arguments:
      $yamlSourceDriver: '@a2b.source.yaml'
      $yamlDestinationDriver: '@a2b.destination.yaml'
  App\Command\DataEncountersMergeCommand:
    arguments:
      $dataPath: '%data_path%'
  App\Command\DataEncountersSortCommand:
    arguments:
      $dataPath: '%data_path%'
  App\Command\ExportLocationMapCommand:
    arguments:
      $assetPath: '%asset_path%'
  
  App\CommonMark\Extension\PoketoolsCommonMarkExtension:
  App\CommonMark\Block\Parser\CallableParser:
    arguments:
      $version: '@app.active_version'
      $jsonEncoder: '@serializer.encoder.json'
  App\CommonMark\Block\Renderer\CallableRenderer:
    arguments:
      $fragmentHandler: '@fragment.handler'
  App\CommonMark\Inline\Parser\CloseBracketInternalLinkParser:
    arguments:
      $version: '@app.active_version'
  
  App\EventSubscriber\DexVersionSubscriber:
    arguments:
      $defaultVersionSlug: '%default_version%'
  
  App\Helpers\Labeler:
    arguments:
      $activeVersion: '@app.active_version'
  
  App\Repository\VersionRepository:
    arguments:
      $defaultVersionSlug: '%default_version%'
  
  App\Twig\AppExtensionRuntime:
    arguments:
      $activeVersion: '@app.active_version'
      $projectDir: '%kernel.project_dir%'
  App\Twig\AssetHelperExtensionRuntime:
    arguments:
      $projectDir: '%kernel.project_dir%'
  
  # VENDORS
  PhpScience\TextRank\Tool\StopWords\English:
  PhpScience\TextRank\TextRankFacade:
    calls:
      - method: setStopWords
        arguments:
          - '@PhpScience\TextRank\Tool\StopWords\English'
  
  League\CommonMark\Environment:
    calls:
      - method: addExtension
        arguments:
          - '@App\CommonMark\Extension\PoketoolsCommonMarkExtension'
  League\CommonMark\DocParser:
    arguments:
      - '@League\CommonMark\Environment'
  League\CommonMark\HtmlRenderer:
    arguments:
      - '@League\CommonMark\Environment'
  League\CommonMark\CommonMarkConverter:
    arguments:
      - '%commonmark_config%'
      - '@League\CommonMark\Environment'
