<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Base migration
 */
final class Version20191119200300 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Base database';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SEQUENCE move_effect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_shape_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE encounter_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE encounter_condition_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE version_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokedex_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_habitat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE shop_item_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_pocket_in_version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE berry_firmness_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE location_area_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_pocket_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_flag_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region_in_version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE feature_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE shop_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_ailment_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region_map_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_species_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_wild_held_item_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE gender_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_learn_method_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE berry_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_color_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE stat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE berry_flavor_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_in_version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_shape_in_version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE location_in_version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contest_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE evolution_trigger_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE growth_rate_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_evolution_condition_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokeblock_color_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_target_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE contest_effect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE generation_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pal_park_area_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE time_of_day_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_chart_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE region_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE machine_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_effect_in_version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ability_in_version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE egg_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE weather_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE battle_style_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_move_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_in_version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE encounter_method_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE super_contest_effect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE ability_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE characteristic_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE encounter_condition_state_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokeathlon_stat_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_species_in_version_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_damage_class_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE nature_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE item_fling_effect_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE pokemon_form_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE move_flag_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE move_effect (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE move_category (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE location (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_shape (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE encounter (id INT NOT NULL, location_area_id INT DEFAULT NULL, method_id INT DEFAULT NULL, pokemon_id INT DEFAULT NULL, version_id INT DEFAULT NULL, chance INT DEFAULT NULL, note TEXT DEFAULT NULL, position INT NOT NULL, level_min INT NOT NULL, level_max INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_69D229CA534A5338 ON encounter (location_area_id)');
        $this->addSql('CREATE INDEX IDX_69D229CA19883967 ON encounter (method_id)');
        $this->addSql('CREATE INDEX IDX_69D229CA2FE71C3E ON encounter (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_69D229CA4BBC2705 ON encounter (version_id)');
        $this->addSql('CREATE TABLE encounter_encounter_condition_state (encounter_id INT NOT NULL, encounter_condition_state_id INT NOT NULL, PRIMARY KEY(encounter_id, encounter_condition_state_id))');
        $this->addSql('CREATE INDEX IDX_3D2737F2D6E2FADC ON encounter_encounter_condition_state (encounter_id)');
        $this->addSql('CREATE INDEX IDX_3D2737F24D8C0238 ON encounter_encounter_condition_state (encounter_condition_state_id)');
        $this->addSql('CREATE TABLE encounter_condition (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE version_group (id INT NOT NULL, generation_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A1C90C0553A6EC4 ON version_group (generation_id)');
        $this->addSql('CREATE TABLE version_group_feature (version_group_id INT NOT NULL, feature_id INT NOT NULL, PRIMARY KEY(version_group_id, feature_id))');
        $this->addSql('CREATE INDEX IDX_5967081C92AE854F ON version_group_feature (version_group_id)');
        $this->addSql('CREATE INDEX IDX_5967081C60E4B879 ON version_group_feature (feature_id)');
        $this->addSql('CREATE TABLE version (id INT NOT NULL, version_group_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF1CD3C392AE854F ON version (version_group_id)');
        $this->addSql('CREATE TABLE pokedex (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, is_default BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokedex_version_group (pokedex_id INT NOT NULL, version_group_id INT NOT NULL, PRIMARY KEY(pokedex_id, version_group_id))');
        $this->addSql('CREATE INDEX IDX_66CF0887372A5D14 ON pokedex_version_group (pokedex_id)');
        $this->addSql('CREATE INDEX IDX_66CF088792AE854F ON pokedex_version_group (version_group_id)');
        $this->addSql('CREATE TABLE pokemon_habitat (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE shop_item (id INT NOT NULL, shop_id INT DEFAULT NULL, item_id INT DEFAULT NULL, buy INT NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DEE9C3654D16C4DD ON shop_item (shop_id)');
        $this->addSql('CREATE INDEX IDX_DEE9C365126F525E ON shop_item (item_id)');
        $this->addSql('CREATE TABLE item_pocket_in_version_group (id INT NOT NULL, parent_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, icon VARCHAR(255) DEFAULT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A4B19D3727ACA70 ON item_pocket_in_version_group (parent_id)');
        $this->addSql('CREATE INDEX IDX_6A4B19D392AE854F ON item_pocket_in_version_group (version_group_id)');
        $this->addSql('CREATE TABLE berry_firmness (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE location_area (id INT NOT NULL, location_id INT DEFAULT NULL, tree_parent_id INT DEFAULT NULL, tree_path VARCHAR(255) DEFAULT NULL, tree_level INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, is_default BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5790882864D218E ON location_area (location_id)');
        $this->addSql('CREATE INDEX IDX_57908828B5CEAE2F ON location_area (tree_parent_id)');
        $this->addSql('CREATE TABLE item_pocket (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE item_flag (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE region_in_version_group (id INT NOT NULL, parent_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_48A5BF84727ACA70 ON region_in_version_group (parent_id)');
        $this->addSql('CREATE INDEX IDX_48A5BF8492AE854F ON region_in_version_group (version_group_id)');
        $this->addSql('CREATE TABLE feature (id INT NOT NULL, slug VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE shop (id INT NOT NULL, location_area_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, is_default BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AC6A4CA2534A5338 ON shop (location_area_id)');
        $this->addSql('CREATE TABLE pokemon_pal_park_data (pokemon_id INT NOT NULL, area_id INT NOT NULL, score INT NOT NULL, rate INT NOT NULL, PRIMARY KEY(pokemon_id, area_id))');
        $this->addSql('CREATE INDEX IDX_283A075E2FE71C3E ON pokemon_pal_park_data (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_283A075EBD0F409C ON pokemon_pal_park_data (area_id)');
        $this->addSql('CREATE TABLE move_ailment (id INT NOT NULL, volatile BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE region_map (id INT NOT NULL, region_id INT DEFAULT NULL, url VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E3E0415298260155 ON region_map (region_id)');
        $this->addSql('CREATE TABLE pokemon_art (url VARCHAR(255) NOT NULL, pokemon_form_id INT NOT NULL, PRIMARY KEY(pokemon_form_id, url))');
        $this->addSql('CREATE INDEX IDX_56AF4470339CE7EC ON pokemon_art (pokemon_form_id)');
        $this->addSql('CREATE TABLE pokemon_sprite (url VARCHAR(255) NOT NULL, pokemon_form_id INT NOT NULL, PRIMARY KEY(pokemon_form_id, url))');
        $this->addSql('CREATE INDEX IDX_59F4F3CA339CE7EC ON pokemon_sprite (pokemon_form_id)');
        $this->addSql('CREATE TABLE pokemon_species (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_wild_held_item (id INT NOT NULL, pokemon_id INT DEFAULT NULL, version_id INT DEFAULT NULL, item_id INT DEFAULT NULL, rate INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E1C77AC12FE71C3E ON pokemon_wild_held_item (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_E1C77AC14BBC2705 ON pokemon_wild_held_item (version_id)');
        $this->addSql('CREATE INDEX IDX_E1C77AC1126F525E ON pokemon_wild_held_item (item_id)');
        $this->addSql('CREATE TABLE gender (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE move_learn_method (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE berry_flavor_level (berry_id INT NOT NULL, flavor_id INT NOT NULL, level INT NOT NULL, PRIMARY KEY(berry_id, flavor_id))');
        $this->addSql('CREATE INDEX IDX_6D816E2564ADF7BC ON berry_flavor_level (berry_id)');
        $this->addSql('CREATE INDEX IDX_6D816E25FDDA6450 ON berry_flavor_level (flavor_id)');
        $this->addSql('CREATE TABLE berry (id INT NOT NULL, firmness_id INT DEFAULT NULL, natural_gift_type_id INT DEFAULT NULL, natural_gift_power INT DEFAULT NULL, size TEXT NOT NULL, growth_time TEXT NOT NULL, water INT DEFAULT NULL, weeds INT DEFAULT NULL, pests INT DEFAULT NULL, smoothness INT DEFAULT NULL, harvest_min INT NOT NULL, harvest_max INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4A8DBAD3B6E7BC0A ON berry (firmness_id)');
        $this->addSql('CREATE INDEX IDX_4A8DBAD32E8FD640 ON berry (natural_gift_type_id)');
        $this->addSql('COMMENT ON COLUMN berry.size IS \'(DC2Type:safe_object)\'');
        $this->addSql('COMMENT ON COLUMN berry.growth_time IS \'(DC2Type:safe_object)\'');
        $this->addSql('CREATE TABLE pokemon_color (id INT NOT NULL, css_color VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_flavor_text (pokemon_id INT NOT NULL, version_id INT NOT NULL, flavor_text TEXT DEFAULT NULL, position INT NOT NULL, PRIMARY KEY(pokemon_id, version_id))');
        $this->addSql('CREATE INDEX IDX_21830D352FE71C3E ON pokemon_flavor_text (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_21830D354BBC2705 ON pokemon_flavor_text (version_id)');
        $this->addSql('CREATE TABLE stat (id INT NOT NULL, damage_class_id INT DEFAULT NULL, battle_only BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_20B8FF219883C12E ON stat (damage_class_id)');
        $this->addSql('CREATE TABLE pokemon_ability (pokemon_id INT NOT NULL, ability_id INT NOT NULL, hidden BOOLEAN NOT NULL, position INT NOT NULL, PRIMARY KEY(pokemon_id, ability_id))');
        $this->addSql('CREATE INDEX IDX_59A592AD2FE71C3E ON pokemon_ability (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_59A592AD8016D8B2 ON pokemon_ability (ability_id)');
        $this->addSql('CREATE TABLE berry_flavor (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE move_in_version_group (id INT NOT NULL, parent_id INT DEFAULT NULL, type_id INT DEFAULT NULL, target_id INT DEFAULT NULL, damage_class_id INT DEFAULT NULL, effect_id INT DEFAULT NULL, contest_type_id INT DEFAULT NULL, contest_effect_id INT DEFAULT NULL, super_contest_effect_id INT DEFAULT NULL, ailment_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, power INT DEFAULT NULL, pp INT DEFAULT NULL, accuracy INT DEFAULT NULL, priority INT NOT NULL, effect_chance INT DEFAULT NULL, stat_change_chance INT DEFAULT NULL, ailment_chance INT DEFAULT NULL, drain INT DEFAULT NULL, recoil INT DEFAULT NULL, healing INT DEFAULT NULL, crit_rate_bonus INT DEFAULT NULL, flinch_chance INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, flavor_text TEXT DEFAULT NULL, hits_min INT NOT NULL, hits_max INT NOT NULL, turns_min INT NOT NULL, turns_max INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_EC5118E5727ACA70 ON move_in_version_group (parent_id)');
        $this->addSql('CREATE INDEX IDX_EC5118E5C54C8C93 ON move_in_version_group (type_id)');
        $this->addSql('CREATE INDEX IDX_EC5118E5158E0B66 ON move_in_version_group (target_id)');
        $this->addSql('CREATE INDEX IDX_EC5118E59883C12E ON move_in_version_group (damage_class_id)');
        $this->addSql('CREATE INDEX IDX_EC5118E5F5E9B83B ON move_in_version_group (effect_id)');
        $this->addSql('CREATE INDEX IDX_EC5118E5C8145F78 ON move_in_version_group (contest_type_id)');
        $this->addSql('CREATE INDEX IDX_EC5118E557B91C2A ON move_in_version_group (contest_effect_id)');
        $this->addSql('CREATE INDEX IDX_EC5118E57E891A9F ON move_in_version_group (super_contest_effect_id)');
        $this->addSql('CREATE INDEX IDX_EC5118E5432CD43A ON move_in_version_group (ailment_id)');
        $this->addSql('CREATE INDEX IDX_EC5118E592AE854F ON move_in_version_group (version_group_id)');
        $this->addSql('CREATE TABLE move_in_version_group_contest_combo (move_in_version_group_first_id INT NOT NULL, move_in_version_group_second_id INT NOT NULL, PRIMARY KEY(move_in_version_group_first_id, move_in_version_group_second_id))');
        $this->addSql('CREATE INDEX IDX_FDE95C5EFD56F0FF ON move_in_version_group_contest_combo (move_in_version_group_first_id)');
        $this->addSql('CREATE INDEX IDX_FDE95C5E2955A3B6 ON move_in_version_group_contest_combo (move_in_version_group_second_id)');
        $this->addSql('CREATE TABLE move_in_version_group_super_contest_combo (move_in_version_group_first_id INT NOT NULL, move_in_version_group_second_id INT NOT NULL, PRIMARY KEY(move_in_version_group_first_id, move_in_version_group_second_id))');
        $this->addSql('CREATE INDEX IDX_48339674FD56F0FF ON move_in_version_group_super_contest_combo (move_in_version_group_first_id)');
        $this->addSql('CREATE INDEX IDX_483396742955A3B6 ON move_in_version_group_super_contest_combo (move_in_version_group_second_id)');
        $this->addSql('CREATE TABLE move_in_version_group_move_flag (move_in_version_group_id INT NOT NULL, move_flag_id INT NOT NULL, PRIMARY KEY(move_in_version_group_id, move_flag_id))');
        $this->addSql('CREATE INDEX IDX_95F6F54571F2EAC ON move_in_version_group_move_flag (move_in_version_group_id)');
        $this->addSql('CREATE INDEX IDX_95F6F54635222B2 ON move_in_version_group_move_flag (move_flag_id)');
        $this->addSql('CREATE TABLE move_in_version_group_move_category (move_in_version_group_id INT NOT NULL, move_category_id INT NOT NULL, PRIMARY KEY(move_in_version_group_id, move_category_id))');
        $this->addSql('CREATE INDEX IDX_B3190C6C571F2EAC ON move_in_version_group_move_category (move_in_version_group_id)');
        $this->addSql('CREATE INDEX IDX_B3190C6CFC597A38 ON move_in_version_group_move_category (move_category_id)');
        $this->addSql('CREATE TABLE pokemon_shape_in_version_group (id INT NOT NULL, parent_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, taxonomy_name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B455F65F727ACA70 ON pokemon_shape_in_version_group (parent_id)');
        $this->addSql('CREATE INDEX IDX_B455F65F92AE854F ON pokemon_shape_in_version_group (version_group_id)');
        $this->addSql('CREATE TABLE nature_pokeathlon_stat_change (nature_id INT NOT NULL, pokeathlon_stat_id INT NOT NULL, max_change INT NOT NULL, PRIMARY KEY(nature_id, pokeathlon_stat_id))');
        $this->addSql('CREATE INDEX IDX_2388F94A3BCB2E4B ON nature_pokeathlon_stat_change (nature_id)');
        $this->addSql('CREATE INDEX IDX_2388F94ABA4F101C ON nature_pokeathlon_stat_change (pokeathlon_stat_id)');
        $this->addSql('CREATE TABLE item_category (id INT NOT NULL, tree_parent_id INT DEFAULT NULL, tree_path VARCHAR(255) DEFAULT NULL, tree_level INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6A41D10AB5CEAE2F ON item_category (tree_parent_id)');
        $this->addSql('CREATE TABLE location_in_version_group (id INT NOT NULL, parent_id INT DEFAULT NULL, region_id INT DEFAULT NULL, super_location_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, tree_path VARCHAR(255) DEFAULT NULL, tree_level INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_C23AF9B7727ACA70 ON location_in_version_group (parent_id)');
        $this->addSql('CREATE INDEX IDX_C23AF9B798260155 ON location_in_version_group (region_id)');
        $this->addSql('CREATE INDEX IDX_C23AF9B7AC51AD7D ON location_in_version_group (super_location_id)');
        $this->addSql('CREATE INDEX IDX_C23AF9B792AE854F ON location_in_version_group (version_group_id)');
        $this->addSql('CREATE TABLE move (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE contest_type (id INT NOT NULL, berry_flavor_id INT DEFAULT NULL, pokeblock_color_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_47B547E2F16F0138 ON contest_type (berry_flavor_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_47B547E2F829F811 ON contest_type (pokeblock_color_id)');
        $this->addSql('CREATE TABLE type_efficacy (type_chart_id INT NOT NULL, attacking_type_id INT NOT NULL, defending_type_id INT NOT NULL, efficacy INT NOT NULL, position INT NOT NULL, PRIMARY KEY(type_chart_id, attacking_type_id, defending_type_id))');
        $this->addSql('CREATE INDEX IDX_95B0DEE8730719F6 ON type_efficacy (type_chart_id)');
        $this->addSql('CREATE INDEX IDX_95B0DEE84963FFFC ON type_efficacy (attacking_type_id)');
        $this->addSql('CREATE INDEX IDX_95B0DEE83572E2B5 ON type_efficacy (defending_type_id)');
        $this->addSql('CREATE TABLE evolution_trigger (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE growth_rate (id INT NOT NULL, formula TEXT NOT NULL, expression TEXT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_evolution_condition (id INT NOT NULL, pokemon_id INT DEFAULT NULL, evolution_trigger_id INT DEFAULT NULL, held_item_id INT DEFAULT NULL, gender_id INT DEFAULT NULL, knows_move_id INT DEFAULT NULL, party_species_id INT DEFAULT NULL, traded_for_species_id INT DEFAULT NULL, time_of_day_id INT DEFAULT NULL, trigger_item_id INT DEFAULT NULL, knows_move_type_id INT DEFAULT NULL, overworld_weather_id INT DEFAULT NULL, party_type_id INT DEFAULT NULL, discr VARCHAR(255) NOT NULL, console_inverted BOOLEAN DEFAULT NULL, minimum_level INT DEFAULT NULL, physical_stats_difference INT DEFAULT NULL, minimum_happiness INT DEFAULT NULL, minimum_beauty INT DEFAULT NULL, minimum_affection INT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1814A35E2FE71C3E ON pokemon_evolution_condition (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_1814A35EAD65CE5B ON pokemon_evolution_condition (evolution_trigger_id)');
        $this->addSql('CREATE INDEX IDX_1814A35EBD59BEFF ON pokemon_evolution_condition (held_item_id)');
        $this->addSql('CREATE INDEX IDX_1814A35E708A0E0 ON pokemon_evolution_condition (gender_id)');
        $this->addSql('CREATE INDEX IDX_1814A35E4515E0DA ON pokemon_evolution_condition (knows_move_id)');
        $this->addSql('CREATE INDEX IDX_1814A35EBADA252C ON pokemon_evolution_condition (party_species_id)');
        $this->addSql('CREATE INDEX IDX_1814A35EB19B8335 ON pokemon_evolution_condition (traded_for_species_id)');
        $this->addSql('CREATE INDEX IDX_1814A35E8CBC81E4 ON pokemon_evolution_condition (time_of_day_id)');
        $this->addSql('CREATE INDEX IDX_1814A35E162F5567 ON pokemon_evolution_condition (trigger_item_id)');
        $this->addSql('CREATE INDEX IDX_1814A35E91901C91 ON pokemon_evolution_condition (knows_move_type_id)');
        $this->addSql('CREATE INDEX IDX_1814A35E8AD2EE75 ON pokemon_evolution_condition (overworld_weather_id)');
        $this->addSql('CREATE INDEX IDX_1814A35ED7BD13B8 ON pokemon_evolution_condition (party_type_id)');
        $this->addSql('CREATE TABLE location_evolution_condition_location_in_version_group (location_evolution_condition_id INT NOT NULL, location_in_version_group_id INT NOT NULL, PRIMARY KEY(location_evolution_condition_id, location_in_version_group_id))');
        $this->addSql('CREATE INDEX IDX_9356496CA208B6FF ON location_evolution_condition_location_in_version_group (location_evolution_condition_id)');
        $this->addSql('CREATE INDEX IDX_9356496CA522AE21 ON location_evolution_condition_location_in_version_group (location_in_version_group_id)');
        $this->addSql('CREATE TABLE pokeblock_color (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE move_target (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE contest_effect (id INT NOT NULL, appeal INT NOT NULL, jam INT NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, flavor_text TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE generation (id INT NOT NULL, number INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE move_stat_change (move_id INT NOT NULL, stat_id INT NOT NULL, change INT NOT NULL, PRIMARY KEY(move_id, stat_id))');
        $this->addSql('CREATE INDEX IDX_5AF08B766DC541A8 ON move_stat_change (move_id)');
        $this->addSql('CREATE INDEX IDX_5AF08B769502F0B ON move_stat_change (stat_id)');
        $this->addSql('CREATE TABLE item (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pal_park_area (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE time_of_day (id INT NOT NULL, generation_id INT DEFAULT NULL, starts TIME(0) WITHOUT TIME ZONE NOT NULL, ends TIME(0) WITHOUT TIME ZONE NOT NULL, position INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8E6B3E41553A6EC4 ON time_of_day (generation_id)');
        $this->addSql('COMMENT ON COLUMN time_of_day.starts IS \'(DC2Type:chronos_time)\'');
        $this->addSql('COMMENT ON COLUMN time_of_day.ends IS \'(DC2Type:chronos_time)\'');
        $this->addSql('CREATE TABLE pokemon_type (pokemon_id INT NOT NULL, type_id INT NOT NULL, position INT NOT NULL, PRIMARY KEY(pokemon_id, type_id))');
        $this->addSql('CREATE INDEX IDX_B077296A2FE71C3E ON pokemon_type (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_B077296AC54C8C93 ON pokemon_type (type_id)');
        $this->addSql('CREATE TABLE pokemon_stat (pokemon_id INT NOT NULL, stat_id INT NOT NULL, base_value INT NOT NULL, effort_change INT NOT NULL, position INT NOT NULL, PRIMARY KEY(pokemon_id, stat_id))');
        $this->addSql('CREATE INDEX IDX_1C1181622FE71C3E ON pokemon_stat (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_1C1181629502F0B ON pokemon_stat (stat_id)');
        $this->addSql('CREATE TABLE location_map (location_id INT NOT NULL, map_id INT DEFAULT NULL, overlay TEXT NOT NULL, z_index INT NOT NULL, PRIMARY KEY(location_id))');
        $this->addSql('CREATE INDEX IDX_F27F212E53C55F64 ON location_map (map_id)');
        $this->addSql('CREATE TABLE type_chart (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE type_chart_version_group (type_chart_id INT NOT NULL, version_group_id INT NOT NULL, PRIMARY KEY(type_chart_id, version_group_id))');
        $this->addSql('CREATE INDEX IDX_50AE1CD8730719F6 ON type_chart_version_group (type_chart_id)');
        $this->addSql('CREATE INDEX IDX_50AE1CD892AE854F ON type_chart_version_group (version_group_id)');
        $this->addSql('CREATE TABLE region (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE machine (id INT NOT NULL, move_id INT DEFAULT NULL, type VARCHAR(255) NOT NULL, number INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1505DF846DC541A8 ON machine (move_id)');
        $this->addSql('CREATE TABLE move_effect_in_version_group (id INT NOT NULL, parent_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_AC1D016727ACA70 ON move_effect_in_version_group (parent_id)');
        $this->addSql('CREATE INDEX IDX_AC1D01692AE854F ON move_effect_in_version_group (version_group_id)');
        $this->addSql('CREATE TABLE ability_in_version_group (id INT NOT NULL, parent_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, flavor_text TEXT DEFAULT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CAF7E8B727ACA70 ON ability_in_version_group (parent_id)');
        $this->addSql('CREATE INDEX IDX_CAF7E8B92AE854F ON ability_in_version_group (version_group_id)');
        $this->addSql('CREATE TABLE egg_group (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE weather (id INT NOT NULL, battle_only BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE battle_style (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_move (id INT NOT NULL, pokemon_id INT DEFAULT NULL, move_id INT DEFAULT NULL, learn_method_id INT DEFAULT NULL, machine_id INT DEFAULT NULL, level INT DEFAULT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D397493B2FE71C3E ON pokemon_move (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_D397493B6DC541A8 ON pokemon_move (move_id)');
        $this->addSql('CREATE INDEX IDX_D397493B764E5F26 ON pokemon_move (learn_method_id)');
        $this->addSql('CREATE INDEX IDX_D397493BF6B75B26 ON pokemon_move (machine_id)');
        $this->addSql('CREATE TABLE item_in_version_group (id INT NOT NULL, parent_id INT DEFAULT NULL, category_id INT DEFAULT NULL, pocket_id INT DEFAULT NULL, fling_effect_id INT DEFAULT NULL, berry_id INT DEFAULT NULL, machine_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, buy INT DEFAULT NULL, sell INT DEFAULT NULL, fling_power INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, flavor_text TEXT DEFAULT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8B593FAC727ACA70 ON item_in_version_group (parent_id)');
        $this->addSql('CREATE INDEX IDX_8B593FAC12469DE2 ON item_in_version_group (category_id)');
        $this->addSql('CREATE INDEX IDX_8B593FACEB831F59 ON item_in_version_group (pocket_id)');
        $this->addSql('CREATE INDEX IDX_8B593FAC7B2A11B9 ON item_in_version_group (fling_effect_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B593FAC64ADF7BC ON item_in_version_group (berry_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8B593FACF6B75B26 ON item_in_version_group (machine_id)');
        $this->addSql('CREATE INDEX IDX_8B593FAC92AE854F ON item_in_version_group (version_group_id)');
        $this->addSql('CREATE TABLE item_in_version_group_item_flag (item_in_version_group_id INT NOT NULL, item_flag_id INT NOT NULL, PRIMARY KEY(item_in_version_group_id, item_flag_id))');
        $this->addSql('CREATE INDEX IDX_D6CCBDC5FC4AA2D3 ON item_in_version_group_item_flag (item_in_version_group_id)');
        $this->addSql('CREATE INDEX IDX_D6CCBDC59AC2C2B1 ON item_in_version_group_item_flag (item_flag_id)');
        $this->addSql('CREATE TABLE encounter_method (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE super_contest_effect (id INT NOT NULL, appeal INT NOT NULL, flavor_text TEXT DEFAULT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE ability (id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE nature_battle_style_preference (nature_id INT NOT NULL, battle_style_id INT NOT NULL, low_hp_chance INT NOT NULL, high_hp_chance INT NOT NULL, PRIMARY KEY(nature_id, battle_style_id))');
        $this->addSql('CREATE INDEX IDX_D654F2BE3BCB2E4B ON nature_battle_style_preference (nature_id)');
        $this->addSql('CREATE INDEX IDX_D654F2BE6EBCCF22 ON nature_battle_style_preference (battle_style_id)');
        $this->addSql('CREATE TABLE characteristic (id INT NOT NULL, stat_id INT DEFAULT NULL, iv_determinator INT NOT NULL, flavor_text TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_522FA9509502F0B ON characteristic (stat_id)');
        $this->addSql('CREATE TABLE pokemon_species_pokedex_number (species_id INT NOT NULL, pokedex_id INT NOT NULL, number INT NOT NULL, is_default BOOLEAN NOT NULL, PRIMARY KEY(species_id, pokedex_id))');
        $this->addSql('CREATE INDEX IDX_B88F6276B2A1D860 ON pokemon_species_pokedex_number (species_id)');
        $this->addSql('CREATE INDEX IDX_B88F6276372A5D14 ON pokemon_species_pokedex_number (pokedex_id)');
        $this->addSql('CREATE TABLE encounter_condition_state (id INT NOT NULL, condition_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, is_default BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_266469AB887793B6 ON encounter_condition_state (condition_id)');
        $this->addSql('CREATE TABLE pokemon_form_pokeathlon_stat (pokemon_form_id INT NOT NULL, pokeathlon_stat_id INT NOT NULL, base_value INT NOT NULL, position INT NOT NULL, range_min INT NOT NULL, range_max INT NOT NULL, PRIMARY KEY(pokemon_form_id, pokeathlon_stat_id))');
        $this->addSql('CREATE INDEX IDX_89C8AD84339CE7EC ON pokemon_form_pokeathlon_stat (pokemon_form_id)');
        $this->addSql('CREATE INDEX IDX_89C8AD84BA4F101C ON pokemon_form_pokeathlon_stat (pokeathlon_stat_id)');
        $this->addSql('CREATE TABLE pokeathlon_stat (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_species_in_version_group (id INT NOT NULL, parent_id INT DEFAULT NULL, version_group_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_E8EF0319727ACA70 ON pokemon_species_in_version_group (parent_id)');
        $this->addSql('CREATE INDEX IDX_E8EF031992AE854F ON pokemon_species_in_version_group (version_group_id)');
        $this->addSql('CREATE TABLE type (id INT NOT NULL, damage_class_id INT DEFAULT NULL, hidden BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8CDE57299883C12E ON type (damage_class_id)');
        $this->addSql('CREATE TABLE move_damage_class (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, position INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon (id INT NOT NULL, species_id INT DEFAULT NULL, evolution_parent_id INT DEFAULT NULL, color_id INT DEFAULT NULL, shape_id INT DEFAULT NULL, habitat_id INT DEFAULT NULL, growth_rate_id INT DEFAULT NULL, evolution_path VARCHAR(255) DEFAULT NULL, evolution_stage INT DEFAULT NULL, female_rate INT DEFAULT NULL, capture_rate INT NOT NULL, happiness INT DEFAULT NULL, baby BOOLEAN NOT NULL, hatch_steps INT DEFAULT NULL, forms_switchable BOOLEAN NOT NULL, genus TEXT NOT NULL, forms_note TEXT DEFAULT NULL, height TEXT NOT NULL, weight TEXT NOT NULL, experience INT NOT NULL, mega BOOLEAN NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, position INT NOT NULL, is_default BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_62DC90F3B2A1D860 ON pokemon (species_id)');
        $this->addSql('CREATE INDEX IDX_62DC90F3A8680923 ON pokemon (evolution_parent_id)');
        $this->addSql('CREATE INDEX IDX_62DC90F37ADA1FB5 ON pokemon (color_id)');
        $this->addSql('CREATE INDEX IDX_62DC90F350266CBB ON pokemon (shape_id)');
        $this->addSql('CREATE INDEX IDX_62DC90F3AFFE2D26 ON pokemon (habitat_id)');
        $this->addSql('CREATE INDEX IDX_62DC90F3DA36863D ON pokemon (growth_rate_id)');
        $this->addSql('COMMENT ON COLUMN pokemon.height IS \'(DC2Type:safe_object)\'');
        $this->addSql('COMMENT ON COLUMN pokemon.weight IS \'(DC2Type:safe_object)\'');
        $this->addSql('CREATE TABLE pokemon_egg_group (pokemon_id INT NOT NULL, egg_group_id INT NOT NULL, PRIMARY KEY(pokemon_id, egg_group_id))');
        $this->addSql('CREATE INDEX IDX_311E8502FE71C3E ON pokemon_egg_group (pokemon_id)');
        $this->addSql('CREATE INDEX IDX_311E850B76DC94C ON pokemon_egg_group (egg_group_id)');
        $this->addSql('CREATE TABLE nature (id INT NOT NULL, stat_increased_id INT DEFAULT NULL, stat_decreased_id INT DEFAULT NULL, flavor_likes_id INT DEFAULT NULL, flavor_hates_id INT DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B1D882A7C45C76E8 ON nature (stat_increased_id)');
        $this->addSql('CREATE INDEX IDX_B1D882A779D2F042 ON nature (stat_decreased_id)');
        $this->addSql('CREATE INDEX IDX_B1D882A7DF57BAF7 ON nature (flavor_likes_id)');
        $this->addSql('CREATE INDEX IDX_B1D882A79A724A24 ON nature (flavor_hates_id)');
        $this->addSql('CREATE TABLE item_fling_effect (id INT NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE pokemon_form (id INT NOT NULL, pokemon_id INT DEFAULT NULL, form_name TEXT NOT NULL, battle_only BOOLEAN NOT NULL, cry VARCHAR(255) DEFAULT NULL, footprint VARCHAR(255) DEFAULT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, is_default BOOLEAN NOT NULL, position INT NOT NULL, icon VARCHAR(255) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6E21830C2FE71C3E ON pokemon_form (pokemon_id)');
        $this->addSql('CREATE TABLE move_flag (id INT NOT NULL, slug VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, short_description TEXT DEFAULT NULL, description TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('ALTER TABLE encounter ADD CONSTRAINT FK_69D229CA534A5338 FOREIGN KEY (location_area_id) REFERENCES location_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE encounter ADD CONSTRAINT FK_69D229CA19883967 FOREIGN KEY (method_id) REFERENCES encounter_method (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE encounter ADD CONSTRAINT FK_69D229CA2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE encounter ADD CONSTRAINT FK_69D229CA4BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE encounter_encounter_condition_state ADD CONSTRAINT FK_3D2737F2D6E2FADC FOREIGN KEY (encounter_id) REFERENCES encounter (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE encounter_encounter_condition_state ADD CONSTRAINT FK_3D2737F24D8C0238 FOREIGN KEY (encounter_condition_state_id) REFERENCES encounter_condition_state (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE version_group ADD CONSTRAINT FK_6A1C90C0553A6EC4 FOREIGN KEY (generation_id) REFERENCES generation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE version_group_feature ADD CONSTRAINT FK_5967081C92AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE version_group_feature ADD CONSTRAINT FK_5967081C60E4B879 FOREIGN KEY (feature_id) REFERENCES feature (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE version ADD CONSTRAINT FK_BF1CD3C392AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokedex_version_group ADD CONSTRAINT FK_66CF0887372A5D14 FOREIGN KEY (pokedex_id) REFERENCES pokedex (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokedex_version_group ADD CONSTRAINT FK_66CF088792AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shop_item ADD CONSTRAINT FK_DEE9C3654D16C4DD FOREIGN KEY (shop_id) REFERENCES shop (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shop_item ADD CONSTRAINT FK_DEE9C365126F525E FOREIGN KEY (item_id) REFERENCES item_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_pocket_in_version_group ADD CONSTRAINT FK_6A4B19D3727ACA70 FOREIGN KEY (parent_id) REFERENCES item_pocket (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_pocket_in_version_group ADD CONSTRAINT FK_6A4B19D392AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_area ADD CONSTRAINT FK_5790882864D218E FOREIGN KEY (location_id) REFERENCES location_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_area ADD CONSTRAINT FK_57908828B5CEAE2F FOREIGN KEY (tree_parent_id) REFERENCES location_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE region_in_version_group ADD CONSTRAINT FK_48A5BF84727ACA70 FOREIGN KEY (parent_id) REFERENCES region (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE region_in_version_group ADD CONSTRAINT FK_48A5BF8492AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE shop ADD CONSTRAINT FK_AC6A4CA2534A5338 FOREIGN KEY (location_area_id) REFERENCES location_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_pal_park_data ADD CONSTRAINT FK_283A075E2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_pal_park_data ADD CONSTRAINT FK_283A075EBD0F409C FOREIGN KEY (area_id) REFERENCES pal_park_area (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE region_map ADD CONSTRAINT FK_E3E0415298260155 FOREIGN KEY (region_id) REFERENCES region_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_art ADD CONSTRAINT FK_56AF4470339CE7EC FOREIGN KEY (pokemon_form_id) REFERENCES pokemon_form (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_sprite ADD CONSTRAINT FK_59F4F3CA339CE7EC FOREIGN KEY (pokemon_form_id) REFERENCES pokemon_form (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_wild_held_item ADD CONSTRAINT FK_E1C77AC12FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_wild_held_item ADD CONSTRAINT FK_E1C77AC14BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_wild_held_item ADD CONSTRAINT FK_E1C77AC1126F525E FOREIGN KEY (item_id) REFERENCES item_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE berry_flavor_level ADD CONSTRAINT FK_6D816E2564ADF7BC FOREIGN KEY (berry_id) REFERENCES berry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE berry_flavor_level ADD CONSTRAINT FK_6D816E25FDDA6450 FOREIGN KEY (flavor_id) REFERENCES berry_flavor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE berry ADD CONSTRAINT FK_4A8DBAD3B6E7BC0A FOREIGN KEY (firmness_id) REFERENCES berry_firmness (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE berry ADD CONSTRAINT FK_4A8DBAD32E8FD640 FOREIGN KEY (natural_gift_type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_flavor_text ADD CONSTRAINT FK_21830D352FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_flavor_text ADD CONSTRAINT FK_21830D354BBC2705 FOREIGN KEY (version_id) REFERENCES version (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE stat ADD CONSTRAINT FK_20B8FF219883C12E FOREIGN KEY (damage_class_id) REFERENCES move_damage_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_ability ADD CONSTRAINT FK_59A592AD2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_ability ADD CONSTRAINT FK_59A592AD8016D8B2 FOREIGN KEY (ability_id) REFERENCES ability_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E5727ACA70 FOREIGN KEY (parent_id) REFERENCES move (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E5C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E5158E0B66 FOREIGN KEY (target_id) REFERENCES move_target (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E59883C12E FOREIGN KEY (damage_class_id) REFERENCES move_damage_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E5F5E9B83B FOREIGN KEY (effect_id) REFERENCES move_effect_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E5C8145F78 FOREIGN KEY (contest_type_id) REFERENCES contest_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E557B91C2A FOREIGN KEY (contest_effect_id) REFERENCES contest_effect (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E57E891A9F FOREIGN KEY (super_contest_effect_id) REFERENCES super_contest_effect (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E5432CD43A FOREIGN KEY (ailment_id) REFERENCES move_ailment (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group ADD CONSTRAINT FK_EC5118E592AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group_contest_combo ADD CONSTRAINT FK_FDE95C5EFD56F0FF FOREIGN KEY (move_in_version_group_first_id) REFERENCES move_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group_contest_combo ADD CONSTRAINT FK_FDE95C5E2955A3B6 FOREIGN KEY (move_in_version_group_second_id) REFERENCES move_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group_super_contest_combo ADD CONSTRAINT FK_48339674FD56F0FF FOREIGN KEY (move_in_version_group_first_id) REFERENCES move_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group_super_contest_combo ADD CONSTRAINT FK_483396742955A3B6 FOREIGN KEY (move_in_version_group_second_id) REFERENCES move_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group_move_flag ADD CONSTRAINT FK_95F6F54571F2EAC FOREIGN KEY (move_in_version_group_id) REFERENCES move_in_version_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group_move_flag ADD CONSTRAINT FK_95F6F54635222B2 FOREIGN KEY (move_flag_id) REFERENCES move_flag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group_move_category ADD CONSTRAINT FK_B3190C6C571F2EAC FOREIGN KEY (move_in_version_group_id) REFERENCES move_in_version_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_in_version_group_move_category ADD CONSTRAINT FK_B3190C6CFC597A38 FOREIGN KEY (move_category_id) REFERENCES move_category (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_shape_in_version_group ADD CONSTRAINT FK_B455F65F727ACA70 FOREIGN KEY (parent_id) REFERENCES pokemon_shape (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_shape_in_version_group ADD CONSTRAINT FK_B455F65F92AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature_pokeathlon_stat_change ADD CONSTRAINT FK_2388F94A3BCB2E4B FOREIGN KEY (nature_id) REFERENCES nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature_pokeathlon_stat_change ADD CONSTRAINT FK_2388F94ABA4F101C FOREIGN KEY (pokeathlon_stat_id) REFERENCES pokeathlon_stat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_category ADD CONSTRAINT FK_6A41D10AB5CEAE2F FOREIGN KEY (tree_parent_id) REFERENCES item_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_in_version_group ADD CONSTRAINT FK_C23AF9B7727ACA70 FOREIGN KEY (parent_id) REFERENCES location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_in_version_group ADD CONSTRAINT FK_C23AF9B798260155 FOREIGN KEY (region_id) REFERENCES region_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_in_version_group ADD CONSTRAINT FK_C23AF9B7AC51AD7D FOREIGN KEY (super_location_id) REFERENCES location_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_in_version_group ADD CONSTRAINT FK_C23AF9B792AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contest_type ADD CONSTRAINT FK_47B547E2F16F0138 FOREIGN KEY (berry_flavor_id) REFERENCES berry_flavor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contest_type ADD CONSTRAINT FK_47B547E2F829F811 FOREIGN KEY (pokeblock_color_id) REFERENCES pokeblock_color (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type_efficacy ADD CONSTRAINT FK_95B0DEE8730719F6 FOREIGN KEY (type_chart_id) REFERENCES type_chart (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type_efficacy ADD CONSTRAINT FK_95B0DEE84963FFFC FOREIGN KEY (attacking_type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type_efficacy ADD CONSTRAINT FK_95B0DEE83572E2B5 FOREIGN KEY (defending_type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35E2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35EAD65CE5B FOREIGN KEY (evolution_trigger_id) REFERENCES evolution_trigger (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35EBD59BEFF FOREIGN KEY (held_item_id) REFERENCES item_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35E708A0E0 FOREIGN KEY (gender_id) REFERENCES gender (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35E4515E0DA FOREIGN KEY (knows_move_id) REFERENCES move_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35EBADA252C FOREIGN KEY (party_species_id) REFERENCES pokemon_species_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35EB19B8335 FOREIGN KEY (traded_for_species_id) REFERENCES pokemon_species_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35E8CBC81E4 FOREIGN KEY (time_of_day_id) REFERENCES time_of_day (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35E162F5567 FOREIGN KEY (trigger_item_id) REFERENCES item_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35E91901C91 FOREIGN KEY (knows_move_type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35E8AD2EE75 FOREIGN KEY (overworld_weather_id) REFERENCES weather (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_evolution_condition ADD CONSTRAINT FK_1814A35ED7BD13B8 FOREIGN KEY (party_type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_evolution_condition_location_in_version_group ADD CONSTRAINT FK_9356496CA208B6FF FOREIGN KEY (location_evolution_condition_id) REFERENCES pokemon_evolution_condition (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_evolution_condition_location_in_version_group ADD CONSTRAINT FK_9356496CA522AE21 FOREIGN KEY (location_in_version_group_id) REFERENCES location_in_version_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_stat_change ADD CONSTRAINT FK_5AF08B766DC541A8 FOREIGN KEY (move_id) REFERENCES move_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_stat_change ADD CONSTRAINT FK_5AF08B769502F0B FOREIGN KEY (stat_id) REFERENCES stat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE time_of_day ADD CONSTRAINT FK_8E6B3E41553A6EC4 FOREIGN KEY (generation_id) REFERENCES generation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_type ADD CONSTRAINT FK_B077296A2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_type ADD CONSTRAINT FK_B077296AC54C8C93 FOREIGN KEY (type_id) REFERENCES type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_stat ADD CONSTRAINT FK_1C1181622FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_stat ADD CONSTRAINT FK_1C1181629502F0B FOREIGN KEY (stat_id) REFERENCES stat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_map ADD CONSTRAINT FK_F27F212E64D218E FOREIGN KEY (location_id) REFERENCES location_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE location_map ADD CONSTRAINT FK_F27F212E53C55F64 FOREIGN KEY (map_id) REFERENCES region_map (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type_chart_version_group ADD CONSTRAINT FK_50AE1CD8730719F6 FOREIGN KEY (type_chart_id) REFERENCES type_chart (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type_chart_version_group ADD CONSTRAINT FK_50AE1CD892AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE machine ADD CONSTRAINT FK_1505DF846DC541A8 FOREIGN KEY (move_id) REFERENCES move_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_effect_in_version_group ADD CONSTRAINT FK_AC1D016727ACA70 FOREIGN KEY (parent_id) REFERENCES move_effect (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE move_effect_in_version_group ADD CONSTRAINT FK_AC1D01692AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ability_in_version_group ADD CONSTRAINT FK_CAF7E8B727ACA70 FOREIGN KEY (parent_id) REFERENCES ability (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE ability_in_version_group ADD CONSTRAINT FK_CAF7E8B92AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_move ADD CONSTRAINT FK_D397493B2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_move ADD CONSTRAINT FK_D397493B6DC541A8 FOREIGN KEY (move_id) REFERENCES move_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_move ADD CONSTRAINT FK_D397493B764E5F26 FOREIGN KEY (learn_method_id) REFERENCES move_learn_method (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_move ADD CONSTRAINT FK_D397493BF6B75B26 FOREIGN KEY (machine_id) REFERENCES item_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_in_version_group ADD CONSTRAINT FK_8B593FAC727ACA70 FOREIGN KEY (parent_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_in_version_group ADD CONSTRAINT FK_8B593FAC12469DE2 FOREIGN KEY (category_id) REFERENCES item_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_in_version_group ADD CONSTRAINT FK_8B593FACEB831F59 FOREIGN KEY (pocket_id) REFERENCES item_pocket_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_in_version_group ADD CONSTRAINT FK_8B593FAC7B2A11B9 FOREIGN KEY (fling_effect_id) REFERENCES item_fling_effect (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_in_version_group ADD CONSTRAINT FK_8B593FAC64ADF7BC FOREIGN KEY (berry_id) REFERENCES berry (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_in_version_group ADD CONSTRAINT FK_8B593FACF6B75B26 FOREIGN KEY (machine_id) REFERENCES machine (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_in_version_group ADD CONSTRAINT FK_8B593FAC92AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_in_version_group_item_flag ADD CONSTRAINT FK_D6CCBDC5FC4AA2D3 FOREIGN KEY (item_in_version_group_id) REFERENCES item_in_version_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item_in_version_group_item_flag ADD CONSTRAINT FK_D6CCBDC59AC2C2B1 FOREIGN KEY (item_flag_id) REFERENCES item_flag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature_battle_style_preference ADD CONSTRAINT FK_D654F2BE3BCB2E4B FOREIGN KEY (nature_id) REFERENCES nature (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature_battle_style_preference ADD CONSTRAINT FK_D654F2BE6EBCCF22 FOREIGN KEY (battle_style_id) REFERENCES battle_style (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE characteristic ADD CONSTRAINT FK_522FA9509502F0B FOREIGN KEY (stat_id) REFERENCES stat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_species_pokedex_number ADD CONSTRAINT FK_B88F6276B2A1D860 FOREIGN KEY (species_id) REFERENCES pokemon_species_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_species_pokedex_number ADD CONSTRAINT FK_B88F6276372A5D14 FOREIGN KEY (pokedex_id) REFERENCES pokedex (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE encounter_condition_state ADD CONSTRAINT FK_266469AB887793B6 FOREIGN KEY (condition_id) REFERENCES encounter_condition (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_form_pokeathlon_stat ADD CONSTRAINT FK_89C8AD84339CE7EC FOREIGN KEY (pokemon_form_id) REFERENCES pokemon_form (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_form_pokeathlon_stat ADD CONSTRAINT FK_89C8AD84BA4F101C FOREIGN KEY (pokeathlon_stat_id) REFERENCES pokeathlon_stat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_species_in_version_group ADD CONSTRAINT FK_E8EF0319727ACA70 FOREIGN KEY (parent_id) REFERENCES pokemon_species (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_species_in_version_group ADD CONSTRAINT FK_E8EF031992AE854F FOREIGN KEY (version_group_id) REFERENCES version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE57299883C12E FOREIGN KEY (damage_class_id) REFERENCES move_damage_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F3B2A1D860 FOREIGN KEY (species_id) REFERENCES pokemon_species_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F3A8680923 FOREIGN KEY (evolution_parent_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F37ADA1FB5 FOREIGN KEY (color_id) REFERENCES pokemon_color (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F350266CBB FOREIGN KEY (shape_id) REFERENCES pokemon_shape_in_version_group (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F3AFFE2D26 FOREIGN KEY (habitat_id) REFERENCES pokemon_habitat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon ADD CONSTRAINT FK_62DC90F3DA36863D FOREIGN KEY (growth_rate_id) REFERENCES growth_rate (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_egg_group ADD CONSTRAINT FK_311E8502FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_egg_group ADD CONSTRAINT FK_311E850B76DC94C FOREIGN KEY (egg_group_id) REFERENCES egg_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature ADD CONSTRAINT FK_B1D882A7C45C76E8 FOREIGN KEY (stat_increased_id) REFERENCES stat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature ADD CONSTRAINT FK_B1D882A779D2F042 FOREIGN KEY (stat_decreased_id) REFERENCES stat (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature ADD CONSTRAINT FK_B1D882A7DF57BAF7 FOREIGN KEY (flavor_likes_id) REFERENCES berry_flavor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE nature ADD CONSTRAINT FK_B1D882A79A724A24 FOREIGN KEY (flavor_hates_id) REFERENCES berry_flavor (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pokemon_form ADD CONSTRAINT FK_6E21830C2FE71C3E FOREIGN KEY (pokemon_id) REFERENCES pokemon (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on \'postgresql\'.');

        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE move_effect_in_version_group DROP CONSTRAINT FK_AC1D016727ACA70');
        $this->addSql('ALTER TABLE move_in_version_group_move_category DROP CONSTRAINT FK_B3190C6CFC597A38');
        $this->addSql('ALTER TABLE location_in_version_group DROP CONSTRAINT FK_C23AF9B7727ACA70');
        $this->addSql('ALTER TABLE pokemon_shape_in_version_group DROP CONSTRAINT FK_B455F65F727ACA70');
        $this->addSql('ALTER TABLE encounter_encounter_condition_state DROP CONSTRAINT FK_3D2737F2D6E2FADC');
        $this->addSql('ALTER TABLE encounter_condition_state DROP CONSTRAINT FK_266469AB887793B6');
        $this->addSql('ALTER TABLE version_group_feature DROP CONSTRAINT FK_5967081C92AE854F');
        $this->addSql('ALTER TABLE version DROP CONSTRAINT FK_BF1CD3C392AE854F');
        $this->addSql('ALTER TABLE pokedex_version_group DROP CONSTRAINT FK_66CF088792AE854F');
        $this->addSql('ALTER TABLE item_pocket_in_version_group DROP CONSTRAINT FK_6A4B19D392AE854F');
        $this->addSql('ALTER TABLE region_in_version_group DROP CONSTRAINT FK_48A5BF8492AE854F');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E592AE854F');
        $this->addSql('ALTER TABLE pokemon_shape_in_version_group DROP CONSTRAINT FK_B455F65F92AE854F');
        $this->addSql('ALTER TABLE location_in_version_group DROP CONSTRAINT FK_C23AF9B792AE854F');
        $this->addSql('ALTER TABLE type_chart_version_group DROP CONSTRAINT FK_50AE1CD892AE854F');
        $this->addSql('ALTER TABLE move_effect_in_version_group DROP CONSTRAINT FK_AC1D01692AE854F');
        $this->addSql('ALTER TABLE ability_in_version_group DROP CONSTRAINT FK_CAF7E8B92AE854F');
        $this->addSql('ALTER TABLE item_in_version_group DROP CONSTRAINT FK_8B593FAC92AE854F');
        $this->addSql('ALTER TABLE pokemon_species_in_version_group DROP CONSTRAINT FK_E8EF031992AE854F');
        $this->addSql('ALTER TABLE encounter DROP CONSTRAINT FK_69D229CA4BBC2705');
        $this->addSql('ALTER TABLE pokemon_wild_held_item DROP CONSTRAINT FK_E1C77AC14BBC2705');
        $this->addSql('ALTER TABLE pokemon_flavor_text DROP CONSTRAINT FK_21830D354BBC2705');
        $this->addSql('ALTER TABLE pokedex_version_group DROP CONSTRAINT FK_66CF0887372A5D14');
        $this->addSql('ALTER TABLE pokemon_species_pokedex_number DROP CONSTRAINT FK_B88F6276372A5D14');
        $this->addSql('ALTER TABLE pokemon DROP CONSTRAINT FK_62DC90F3AFFE2D26');
        $this->addSql('ALTER TABLE item_in_version_group DROP CONSTRAINT FK_8B593FACEB831F59');
        $this->addSql('ALTER TABLE berry DROP CONSTRAINT FK_4A8DBAD3B6E7BC0A');
        $this->addSql('ALTER TABLE encounter DROP CONSTRAINT FK_69D229CA534A5338');
        $this->addSql('ALTER TABLE location_area DROP CONSTRAINT FK_57908828B5CEAE2F');
        $this->addSql('ALTER TABLE shop DROP CONSTRAINT FK_AC6A4CA2534A5338');
        $this->addSql('ALTER TABLE item_pocket_in_version_group DROP CONSTRAINT FK_6A4B19D3727ACA70');
        $this->addSql('ALTER TABLE item_in_version_group_item_flag DROP CONSTRAINT FK_D6CCBDC59AC2C2B1');
        $this->addSql('ALTER TABLE region_map DROP CONSTRAINT FK_E3E0415298260155');
        $this->addSql('ALTER TABLE location_in_version_group DROP CONSTRAINT FK_C23AF9B798260155');
        $this->addSql('ALTER TABLE version_group_feature DROP CONSTRAINT FK_5967081C60E4B879');
        $this->addSql('ALTER TABLE shop_item DROP CONSTRAINT FK_DEE9C3654D16C4DD');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E5432CD43A');
        $this->addSql('ALTER TABLE location_map DROP CONSTRAINT FK_F27F212E53C55F64');
        $this->addSql('ALTER TABLE pokemon_species_in_version_group DROP CONSTRAINT FK_E8EF0319727ACA70');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35E708A0E0');
        $this->addSql('ALTER TABLE pokemon_move DROP CONSTRAINT FK_D397493B764E5F26');
        $this->addSql('ALTER TABLE berry_flavor_level DROP CONSTRAINT FK_6D816E2564ADF7BC');
        $this->addSql('ALTER TABLE item_in_version_group DROP CONSTRAINT FK_8B593FAC64ADF7BC');
        $this->addSql('ALTER TABLE pokemon DROP CONSTRAINT FK_62DC90F37ADA1FB5');
        $this->addSql('ALTER TABLE move_stat_change DROP CONSTRAINT FK_5AF08B769502F0B');
        $this->addSql('ALTER TABLE pokemon_stat DROP CONSTRAINT FK_1C1181629502F0B');
        $this->addSql('ALTER TABLE characteristic DROP CONSTRAINT FK_522FA9509502F0B');
        $this->addSql('ALTER TABLE nature DROP CONSTRAINT FK_B1D882A7C45C76E8');
        $this->addSql('ALTER TABLE nature DROP CONSTRAINT FK_B1D882A779D2F042');
        $this->addSql('ALTER TABLE berry_flavor_level DROP CONSTRAINT FK_6D816E25FDDA6450');
        $this->addSql('ALTER TABLE contest_type DROP CONSTRAINT FK_47B547E2F16F0138');
        $this->addSql('ALTER TABLE nature DROP CONSTRAINT FK_B1D882A7DF57BAF7');
        $this->addSql('ALTER TABLE nature DROP CONSTRAINT FK_B1D882A79A724A24');
        $this->addSql('ALTER TABLE move_in_version_group_contest_combo DROP CONSTRAINT FK_FDE95C5EFD56F0FF');
        $this->addSql('ALTER TABLE move_in_version_group_contest_combo DROP CONSTRAINT FK_FDE95C5E2955A3B6');
        $this->addSql('ALTER TABLE move_in_version_group_super_contest_combo DROP CONSTRAINT FK_48339674FD56F0FF');
        $this->addSql('ALTER TABLE move_in_version_group_super_contest_combo DROP CONSTRAINT FK_483396742955A3B6');
        $this->addSql('ALTER TABLE move_in_version_group_move_flag DROP CONSTRAINT FK_95F6F54571F2EAC');
        $this->addSql('ALTER TABLE move_in_version_group_move_category DROP CONSTRAINT FK_B3190C6C571F2EAC');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35E4515E0DA');
        $this->addSql('ALTER TABLE move_stat_change DROP CONSTRAINT FK_5AF08B766DC541A8');
        $this->addSql('ALTER TABLE machine DROP CONSTRAINT FK_1505DF846DC541A8');
        $this->addSql('ALTER TABLE pokemon_move DROP CONSTRAINT FK_D397493B6DC541A8');
        $this->addSql('ALTER TABLE pokemon DROP CONSTRAINT FK_62DC90F350266CBB');
        $this->addSql('ALTER TABLE item_category DROP CONSTRAINT FK_6A41D10AB5CEAE2F');
        $this->addSql('ALTER TABLE item_in_version_group DROP CONSTRAINT FK_8B593FAC12469DE2');
        $this->addSql('ALTER TABLE location_area DROP CONSTRAINT FK_5790882864D218E');
        $this->addSql('ALTER TABLE location_in_version_group DROP CONSTRAINT FK_C23AF9B7AC51AD7D');
        $this->addSql('ALTER TABLE location_evolution_condition_location_in_version_group DROP CONSTRAINT FK_9356496CA522AE21');
        $this->addSql('ALTER TABLE location_map DROP CONSTRAINT FK_F27F212E64D218E');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E5727ACA70');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E5C8145F78');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35EAD65CE5B');
        $this->addSql('ALTER TABLE pokemon DROP CONSTRAINT FK_62DC90F3DA36863D');
        $this->addSql('ALTER TABLE location_evolution_condition_location_in_version_group DROP CONSTRAINT FK_9356496CA208B6FF');
        $this->addSql('ALTER TABLE contest_type DROP CONSTRAINT FK_47B547E2F829F811');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E5158E0B66');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E557B91C2A');
        $this->addSql('ALTER TABLE version_group DROP CONSTRAINT FK_6A1C90C0553A6EC4');
        $this->addSql('ALTER TABLE time_of_day DROP CONSTRAINT FK_8E6B3E41553A6EC4');
        $this->addSql('ALTER TABLE item_in_version_group DROP CONSTRAINT FK_8B593FAC727ACA70');
        $this->addSql('ALTER TABLE pokemon_pal_park_data DROP CONSTRAINT FK_283A075EBD0F409C');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35E8CBC81E4');
        $this->addSql('ALTER TABLE type_efficacy DROP CONSTRAINT FK_95B0DEE8730719F6');
        $this->addSql('ALTER TABLE type_chart_version_group DROP CONSTRAINT FK_50AE1CD8730719F6');
        $this->addSql('ALTER TABLE region_in_version_group DROP CONSTRAINT FK_48A5BF84727ACA70');
        $this->addSql('ALTER TABLE item_in_version_group DROP CONSTRAINT FK_8B593FACF6B75B26');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E5F5E9B83B');
        $this->addSql('ALTER TABLE pokemon_ability DROP CONSTRAINT FK_59A592AD8016D8B2');
        $this->addSql('ALTER TABLE pokemon_egg_group DROP CONSTRAINT FK_311E850B76DC94C');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35E8AD2EE75');
        $this->addSql('ALTER TABLE nature_battle_style_preference DROP CONSTRAINT FK_D654F2BE6EBCCF22');
        $this->addSql('ALTER TABLE shop_item DROP CONSTRAINT FK_DEE9C365126F525E');
        $this->addSql('ALTER TABLE pokemon_wild_held_item DROP CONSTRAINT FK_E1C77AC1126F525E');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35EBD59BEFF');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35E162F5567');
        $this->addSql('ALTER TABLE pokemon_move DROP CONSTRAINT FK_D397493BF6B75B26');
        $this->addSql('ALTER TABLE item_in_version_group_item_flag DROP CONSTRAINT FK_D6CCBDC5FC4AA2D3');
        $this->addSql('ALTER TABLE encounter DROP CONSTRAINT FK_69D229CA19883967');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E57E891A9F');
        $this->addSql('ALTER TABLE ability_in_version_group DROP CONSTRAINT FK_CAF7E8B727ACA70');
        $this->addSql('ALTER TABLE encounter_encounter_condition_state DROP CONSTRAINT FK_3D2737F24D8C0238');
        $this->addSql('ALTER TABLE nature_pokeathlon_stat_change DROP CONSTRAINT FK_2388F94ABA4F101C');
        $this->addSql('ALTER TABLE pokemon_form_pokeathlon_stat DROP CONSTRAINT FK_89C8AD84BA4F101C');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35EBADA252C');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35EB19B8335');
        $this->addSql('ALTER TABLE pokemon_species_pokedex_number DROP CONSTRAINT FK_B88F6276B2A1D860');
        $this->addSql('ALTER TABLE pokemon DROP CONSTRAINT FK_62DC90F3B2A1D860');
        $this->addSql('ALTER TABLE berry DROP CONSTRAINT FK_4A8DBAD32E8FD640');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E5C54C8C93');
        $this->addSql('ALTER TABLE type_efficacy DROP CONSTRAINT FK_95B0DEE84963FFFC');
        $this->addSql('ALTER TABLE type_efficacy DROP CONSTRAINT FK_95B0DEE83572E2B5');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35E91901C91');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35ED7BD13B8');
        $this->addSql('ALTER TABLE pokemon_type DROP CONSTRAINT FK_B077296AC54C8C93');
        $this->addSql('ALTER TABLE stat DROP CONSTRAINT FK_20B8FF219883C12E');
        $this->addSql('ALTER TABLE move_in_version_group DROP CONSTRAINT FK_EC5118E59883C12E');
        $this->addSql('ALTER TABLE type DROP CONSTRAINT FK_8CDE57299883C12E');
        $this->addSql('ALTER TABLE encounter DROP CONSTRAINT FK_69D229CA2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_pal_park_data DROP CONSTRAINT FK_283A075E2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_wild_held_item DROP CONSTRAINT FK_E1C77AC12FE71C3E');
        $this->addSql('ALTER TABLE pokemon_flavor_text DROP CONSTRAINT FK_21830D352FE71C3E');
        $this->addSql('ALTER TABLE pokemon_ability DROP CONSTRAINT FK_59A592AD2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_evolution_condition DROP CONSTRAINT FK_1814A35E2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_type DROP CONSTRAINT FK_B077296A2FE71C3E');
        $this->addSql('ALTER TABLE pokemon_stat DROP CONSTRAINT FK_1C1181622FE71C3E');
        $this->addSql('ALTER TABLE pokemon_move DROP CONSTRAINT FK_D397493B2FE71C3E');
        $this->addSql('ALTER TABLE pokemon DROP CONSTRAINT FK_62DC90F3A8680923');
        $this->addSql('ALTER TABLE pokemon_egg_group DROP CONSTRAINT FK_311E8502FE71C3E');
        $this->addSql('ALTER TABLE pokemon_form DROP CONSTRAINT FK_6E21830C2FE71C3E');
        $this->addSql('ALTER TABLE nature_pokeathlon_stat_change DROP CONSTRAINT FK_2388F94A3BCB2E4B');
        $this->addSql('ALTER TABLE nature_battle_style_preference DROP CONSTRAINT FK_D654F2BE3BCB2E4B');
        $this->addSql('ALTER TABLE item_in_version_group DROP CONSTRAINT FK_8B593FAC7B2A11B9');
        $this->addSql('ALTER TABLE pokemon_art DROP CONSTRAINT FK_56AF4470339CE7EC');
        $this->addSql('ALTER TABLE pokemon_sprite DROP CONSTRAINT FK_59F4F3CA339CE7EC');
        $this->addSql('ALTER TABLE pokemon_form_pokeathlon_stat DROP CONSTRAINT FK_89C8AD84339CE7EC');
        $this->addSql('ALTER TABLE move_in_version_group_move_flag DROP CONSTRAINT FK_95F6F54635222B2');
        $this->addSql('DROP SEQUENCE move_effect_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_shape_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE encounter_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE encounter_condition_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE version_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokedex_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_habitat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE shop_item_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_pocket_in_version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE berry_firmness_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE location_area_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_pocket_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_flag_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region_in_version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE feature_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE shop_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_ailment_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region_map_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_species_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_wild_held_item_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE gender_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_learn_method_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE berry_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_color_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE stat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE berry_flavor_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_in_version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_shape_in_version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE location_in_version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contest_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE evolution_trigger_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE growth_rate_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_evolution_condition_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokeblock_color_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_target_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE contest_effect_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE generation_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pal_park_area_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE time_of_day_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_chart_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE region_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE machine_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_effect_in_version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ability_in_version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE egg_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE weather_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE battle_style_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_move_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_in_version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE encounter_method_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE super_contest_effect_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE ability_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE characteristic_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE encounter_condition_state_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokeathlon_stat_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_species_in_version_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_damage_class_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE nature_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE item_fling_effect_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE pokemon_form_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE move_flag_id_seq CASCADE');
        $this->addSql('DROP TABLE move_effect');
        $this->addSql('DROP TABLE move_category');
        $this->addSql('DROP TABLE location');
        $this->addSql('DROP TABLE pokemon_shape');
        $this->addSql('DROP TABLE encounter');
        $this->addSql('DROP TABLE encounter_encounter_condition_state');
        $this->addSql('DROP TABLE encounter_condition');
        $this->addSql('DROP TABLE version_group');
        $this->addSql('DROP TABLE version_group_feature');
        $this->addSql('DROP TABLE version');
        $this->addSql('DROP TABLE pokedex');
        $this->addSql('DROP TABLE pokedex_version_group');
        $this->addSql('DROP TABLE pokemon_habitat');
        $this->addSql('DROP TABLE shop_item');
        $this->addSql('DROP TABLE item_pocket_in_version_group');
        $this->addSql('DROP TABLE berry_firmness');
        $this->addSql('DROP TABLE location_area');
        $this->addSql('DROP TABLE item_pocket');
        $this->addSql('DROP TABLE item_flag');
        $this->addSql('DROP TABLE region_in_version_group');
        $this->addSql('DROP TABLE feature');
        $this->addSql('DROP TABLE shop');
        $this->addSql('DROP TABLE pokemon_pal_park_data');
        $this->addSql('DROP TABLE move_ailment');
        $this->addSql('DROP TABLE region_map');
        $this->addSql('DROP TABLE pokemon_art');
        $this->addSql('DROP TABLE pokemon_sprite');
        $this->addSql('DROP TABLE pokemon_species');
        $this->addSql('DROP TABLE pokemon_wild_held_item');
        $this->addSql('DROP TABLE gender');
        $this->addSql('DROP TABLE move_learn_method');
        $this->addSql('DROP TABLE berry_flavor_level');
        $this->addSql('DROP TABLE berry');
        $this->addSql('DROP TABLE pokemon_color');
        $this->addSql('DROP TABLE pokemon_flavor_text');
        $this->addSql('DROP TABLE stat');
        $this->addSql('DROP TABLE pokemon_ability');
        $this->addSql('DROP TABLE berry_flavor');
        $this->addSql('DROP TABLE move_in_version_group');
        $this->addSql('DROP TABLE move_in_version_group_contest_combo');
        $this->addSql('DROP TABLE move_in_version_group_super_contest_combo');
        $this->addSql('DROP TABLE move_in_version_group_move_flag');
        $this->addSql('DROP TABLE move_in_version_group_move_category');
        $this->addSql('DROP TABLE pokemon_shape_in_version_group');
        $this->addSql('DROP TABLE nature_pokeathlon_stat_change');
        $this->addSql('DROP TABLE item_category');
        $this->addSql('DROP TABLE location_in_version_group');
        $this->addSql('DROP TABLE move');
        $this->addSql('DROP TABLE contest_type');
        $this->addSql('DROP TABLE type_efficacy');
        $this->addSql('DROP TABLE evolution_trigger');
        $this->addSql('DROP TABLE growth_rate');
        $this->addSql('DROP TABLE pokemon_evolution_condition');
        $this->addSql('DROP TABLE location_evolution_condition_location_in_version_group');
        $this->addSql('DROP TABLE pokeblock_color');
        $this->addSql('DROP TABLE move_target');
        $this->addSql('DROP TABLE contest_effect');
        $this->addSql('DROP TABLE generation');
        $this->addSql('DROP TABLE move_stat_change');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE pal_park_area');
        $this->addSql('DROP TABLE time_of_day');
        $this->addSql('DROP TABLE pokemon_type');
        $this->addSql('DROP TABLE pokemon_stat');
        $this->addSql('DROP TABLE location_map');
        $this->addSql('DROP TABLE type_chart');
        $this->addSql('DROP TABLE type_chart_version_group');
        $this->addSql('DROP TABLE region');
        $this->addSql('DROP TABLE machine');
        $this->addSql('DROP TABLE move_effect_in_version_group');
        $this->addSql('DROP TABLE ability_in_version_group');
        $this->addSql('DROP TABLE egg_group');
        $this->addSql('DROP TABLE weather');
        $this->addSql('DROP TABLE battle_style');
        $this->addSql('DROP TABLE pokemon_move');
        $this->addSql('DROP TABLE item_in_version_group');
        $this->addSql('DROP TABLE item_in_version_group_item_flag');
        $this->addSql('DROP TABLE encounter_method');
        $this->addSql('DROP TABLE super_contest_effect');
        $this->addSql('DROP TABLE ability');
        $this->addSql('DROP TABLE nature_battle_style_preference');
        $this->addSql('DROP TABLE characteristic');
        $this->addSql('DROP TABLE pokemon_species_pokedex_number');
        $this->addSql('DROP TABLE encounter_condition_state');
        $this->addSql('DROP TABLE pokemon_form_pokeathlon_stat');
        $this->addSql('DROP TABLE pokeathlon_stat');
        $this->addSql('DROP TABLE pokemon_species_in_version_group');
        $this->addSql('DROP TABLE type');
        $this->addSql('DROP TABLE move_damage_class');
        $this->addSql('DROP TABLE pokemon');
        $this->addSql('DROP TABLE pokemon_egg_group');
        $this->addSql('DROP TABLE nature');
        $this->addSql('DROP TABLE item_fling_effect');
        $this->addSql('DROP TABLE pokemon_form');
        $this->addSql('DROP TABLE move_flag');
    }
}
