json_schema_schema_index:
  path: /
  controller: DragoonBoots\JsonSchemaBundle\Controller\SchemaController::index

json_schema_schema_show:
  path: /{relPath}
  controller: DragoonBoots\JsonSchemaBundle\Controller\SchemaController::show
  requirements:
    relPath: .+
