parameters:
  json_schema.schema_prefix: ~
  json_schema.schema_path: ~

services:
  _defaults:
    public: false
    autowire: false
    autoconfigure: true
  
  DragoonBoots\JsonSchemaBundle\Schema\Inspector:
    alias: '@json_schema.inspector'
  json_schema.inspector:
    class: DragoonBoots\JsonSchemaBundle\Schema\Inspector
    public: true
    arguments:
      $schemaLoader: '@json_schema.loader.path_loader'
  
  JsonSchema\Validator:
    alias: '@json_schema.validator'
  json_schema.validator:
    class: Opis\JsonSchema\Validator
    public: true
    calls:
      - method: setLoader
        arguments:
          - '@json_schema.loader.path_loader'
  
  # Controllers
  DragoonBoots\JsonSchemaBundle\Controller\SchemaController:
    arguments:
      $schemaInspector: '@json_schema.inspector'
      $schemaPath: '%json_schema.schema_path%'
      $schemaPrefix: '%json_schema.schema_prefix%'
  
  # Private helpers
  DragoonBoots\JsonSchemaBundle\Schema\Loader\PathLoader:
    alias: '@json_schema.loader.path_loader'
    
  json_schema.loader.path_loader:
    class: DragoonBoots\JsonSchemaBundle\Schema\Loader\PathLoader
    calls:
      - method: registerPath
        arguments:
          $dir: '%json_schema.schema_path%'
          $uriPrefix: '%json_schema.schema_prefix%'
          
  DragoonBoots\JsonSchemaBundle\Twig\Extension\JsonSchemaBundleExtension:
