apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: poketools
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: elasticsearch
    - port: 9300
      name: discovery
  selector:
    app: elasticsearch
