#######################################
# DEVELOPMENT IMAGE
# (Doesn't load data automaticlly)
#######################################
FROM postgres:12 as db_dev

#######################################
# BASE IMAGE
#######################################
FROM db_dev as db

COPY init.sh /docker-entrypoint-initdb.d/
COPY template.generated.pgdump /initdb.d/
