#######################################
# DEVELOPMENT IMAGE
# (Doesn't load data automaticlly)
#######################################
FROM postgres:11 as db_dev

#######################################
# BASE IMAGE
#######################################
FROM db_dev as db

COPY template.generated.pg.sql /docker-entrypoint-initdb.d/
