map_slugs = {}
map_slugs[0x00] = {
    0x00: {'location': 'petalburg-city', 'area': 'whole-area'},
    0x01: {'location': 'slateport-city', 'area': 'whole-area'},
    0x02: {'location': 'mauville-city', 'area': 'whole-area'},
    0x03: {'location': 'rustboro-city', 'area': 'whole-area'},
    0x04: {'location': 'fortree-city', 'area': 'whole-area'},
    0x05: {'location': 'lilycove-city', 'area': 'whole-area'},
    0x06: {'location': 'mossdeep-city', 'area': 'whole-area'},
    0x07: {'location': 'sootopolis-city', 'area': 'whole-area'},
    0x08: {'location': 'ever-grande-city', 'area': 'whole-area'},
    0x09: {'location': 'littleroot-town', 'area': 'whole-area'},
    0x0A: {'location': 'oldale-town', 'area': 'whole-area'},
    0x0B: {'location': 'dewford-town', 'area': 'whole-area'},
    0x0C: {'location': 'lavaridge-town', 'area': 'whole-area'},
    0x0D: {'location': 'fallarbor-town', 'area': 'whole-area'},
    0x0E: {'location': 'verdanturf-town', 'area': 'whole-area'},
    0x0F: {'location': 'pacifidlog-town', 'area': 'whole-area'},
    0x10: {'location': 'hoenn-route-101', 'area': 'whole-area'},
    0x11: {'location': 'hoenn-route-102', 'area': 'whole-area'},
    0x12: {'location': 'hoenn-route-103', 'area': 'whole-area'},
    0x13: {'location': 'hoenn-route-104', 'area': 'whole-area'},
    0x14: {'location': 'hoenn-route-105', 'area': 'whole-area'},
    0x15: {'location': 'hoenn-route-106', 'area': 'whole-area'},
    0x16: {'location': 'hoenn-route-107', 'area': 'whole-area'},
    0x17: {'location': 'hoenn-route-108', 'area': 'whole-area'},
    0x18: {'location': 'hoenn-route-109', 'area': 'whole-area'},
    0x19: {'location': 'hoenn-route-110', 'area': 'whole-area'},
    0x1A: {'location': 'hoenn-route-111', 'area': 'whole-area'},
    0x1B: {'location': 'hoenn-route-112', 'area': 'whole-area'},
    0x1C: {'location': 'hoenn-route-113', 'area': 'whole-area'},
    0x1D: {'location': 'hoenn-route-114', 'area': 'whole-area'},
    0x1E: {'location': 'hoenn-route-115', 'area': 'whole-area'},
    0x1F: {'location': 'hoenn-route-116', 'area': 'whole-area'},
    0x20: {'location': 'hoenn-route-117', 'area': 'whole-area'},
    0x21: {'location': 'hoenn-route-118', 'area': 'whole-area'},
    0x22: {'location': 'hoenn-route-119', 'area': 'whole-area'},
    0x23: {'location': 'hoenn-route-120', 'area': 'whole-area'},
    0x24: {'location': 'hoenn-route-121', 'area': 'whole-area'},
    0x25: {'location': 'hoenn-route-122', 'area': 'whole-area'},
    0x26: {'location': 'hoenn-route-123', 'area': 'whole-area'},
    0x27: {'location': 'hoenn-route-124', 'area': 'whole-area'},
    0x28: {'location': 'hoenn-route-125', 'area': 'whole-area'},
    0x29: {'location': 'hoenn-route-126', 'area': 'whole-area'},
    0x2A: {'location': 'hoenn-route-127', 'area': 'whole-area'},
    0x2B: {'location': 'hoenn-route-128', 'area': 'whole-area'},
    0x2C: {'location': 'hoenn-route-129', 'area': 'whole-area'},
    0x2D: {'location': 'hoenn-route-130', 'area': 'whole-area'},
    0x2E: {'location': 'hoenn-route-131', 'area': 'whole-area'},
    0x2F: {'location': 'hoenn-route-132', 'area': 'whole-area'},
    0x30: {'location': 'hoenn-route-133', 'area': 'whole-area'},
    0x31: {'location': 'hoenn-route-134', 'area': 'whole-area'},
    0x32: {'location': 'underwater-1', 'area': 'whole-area'},
    0x33: {'location': 'underwater-2', 'area': 'whole-area'},
    0x34: {'location': 'underwater-3', 'area': 'whole-area'},
    0x35: {'location': 'underwater-4', 'area': 'whole-area'},
    0x36: {'location': 'underwater-5', 'area': 'whole-area'},
    0x37: {'location': 'underwater-6', 'area': 'whole-area'},
    0x38: {'location': 'underwater-7', 'area': 'whole-area'},
}
map_slugs[0x01] = {
    0x00: {'location': 'littleroot-town', 'area': 'brendans-house/1f'},
    0x01: {'location': 'littleroot-town', 'area': 'brendans-house/2f'},
    0x02: {'location': 'littleroot-town', 'area': 'mays-house/1f'},
    0x03: {'location': 'littleroot-town', 'area': 'mays-house/2f'},
    0x04: {'location': 'littleroot-town', 'area': 'professor-birchs-lab'},
}
map_slugs[0x02] = {
    0x00: {'location': 'oldale-town', 'area': 'house-1'},
    0x01: {'location': 'oldale-town', 'area': 'house-2'},
    0x02: {'location': 'oldale-town', 'area': 'pokemon-center/1f'},
    0x03: {'location': 'oldale-town', 'area': 'pokemon-center/2f'},
    0x04: {'location': 'oldale-town', 'area': 'mart'},
}
map_slugs[0x03] = {
    0x00: {'location': 'dewford-town', 'area': 'house-1'},
    0x01: {'location': 'dewford-town', 'area': 'pokemon-center/1f'},
    0x02: {'location': 'dewford-town', 'area': 'pokemon-center/2f'},
    0x03: {'location': 'dewford-town', 'area': 'gym'},
    0x04: {'location': 'dewford-town', 'area': 'hall'},
    0x05: {'location': 'dewford-town', 'area': 'house-2'},
}
map_slugs[0x04] = {
    0x00: {'location': 'lavaridge-town', 'area': 'herb-shop'},
    0x01: {'location': 'lavaridge-town', 'area': 'gym/1f'},
    0x02: {'location': 'lavaridge-town', 'area': 'gym/b1f'},
    0x03: {'location': 'lavaridge-town', 'area': 'house'},
    0x04: {'location': 'lavaridge-town', 'area': 'mart'},
    0x05: {'location': 'lavaridge-town', 'area': 'pokemon-center/1f'},
    0x06: {'location': 'lavaridge-town', 'area': 'pokemon-center/2f'},
}
map_slugs[0x05] = {
    0x00: {'location': 'fallarbor-town', 'area': 'mart'},
    0x01: {'location': 'fallarbor-town', 'area': 'battle-tent-lobby'},
    0x02: {'location': 'fallarbor-town', 'area': 'battle-tent-corridor'},
    0x03: {'location': 'fallarbor-town', 'area': 'battle-tent-battle-room'},
    0x04: {'location': 'fallarbor-town', 'area': 'pokemon-center/1f'},
    0x05: {'location': 'fallarbor-town', 'area': 'pokemon-center/2f'},
    0x06: {'location': 'fallarbor-town', 'area': 'cozmos-house'},
    0x07: {'location': 'fallarbor-town', 'area': 'move-relearners-house'},
}
map_slugs[0x06] = {
    0x00: {'location': 'verdanturf-town', 'area': 'battle-tent-lobby'},
    0x01: {'location': 'verdanturf-town', 'area': 'battle-tent-corridor'},
    0x02: {'location': 'verdanturf-town', 'area': 'battle-tent-battle-room'},
    0x03: {'location': 'verdanturf-town', 'area': 'mart'},
    0x04: {'location': 'verdanturf-town', 'area': 'pokemon-center/1f'},
    0x05: {'location': 'verdanturf-town', 'area': 'pokemon-center/2f'},
    0x06: {'location': 'verdanturf-town', 'area': 'wandas-house'},
    0x07: {'location': 'verdanturf-town', 'area': 'friendship-raters-house'},
    0x08: {'location': 'verdanturf-town', 'area': 'house'},
}
map_slugs[0x07] = {
    0x00: {'location': 'pacifidlog-town', 'area': 'pokemon-center/1f'},
    0x01: {'location': 'pacifidlog-town', 'area': 'pokemon-center/2f'},
    0x02: {'location': 'pacifidlog-town', 'area': 'house-1'},
    0x03: {'location': 'pacifidlog-town', 'area': 'house-2'},
    0x04: {'location': 'pacifidlog-town', 'area': 'house-3'},
    0x05: {'location': 'pacifidlog-town', 'area': 'house-4'},
    0x06: {'location': 'pacifidlog-town', 'area': 'house-5'},
}
map_slugs[0x08] = {
    0x00: {'location': 'petalburg-city', 'area': 'wallys-house'},
    0x01: {'location': 'petalburg-city', 'area': 'gym'},
    0x02: {'location': 'petalburg-city', 'area': 'house-1'},
    0x03: {'location': 'petalburg-city', 'area': 'house-2'},
    0x04: {'location': 'petalburg-city', 'area': 'pokemon-center/1f'},
    0x05: {'location': 'petalburg-city', 'area': 'pokemon-center/2f'},
    0x06: {'location': 'petalburg-city', 'area': 'mart'},
}
map_slugs[0x09] = {
    0x00: {'location': 'slateport-city', 'area': 'sterns-shipyard/1f'},
    0x01: {'location': 'slateport-city', 'area': 'sterns-shipyard/2f'},
    0x02: {'location': 'slateport-city', 'area': 'battle-tent-lobby'},
    0x03: {'location': 'slateport-city', 'area': 'battle-tent-corridor'},
    0x04: {'location': 'slateport-city', 'area': 'battle-tent-battle-room'},
    0x05: {'location': 'slateport-city', 'area': 'name-raters-house'},
    0x06: {'location': 'slateport-city', 'area': 'pokemon-fan-club'},
    0x07: {'location': 'slateport-city', 'area': 'oceanic-museum/1f'},
    0x08: {'location': 'slateport-city', 'area': 'oceanic-museum/2f'},
    0x09: {'location': 'slateport-city', 'area': 'harbor'},
    0x0A: {'location': 'slateport-city', 'area': 'house'},
    0x0B: {'location': 'slateport-city', 'area': 'pokemon-center/1f'},
    0x0C: {'location': 'slateport-city', 'area': 'pokemon-center/2f'},
    0x0D: {'location': 'slateport-city', 'area': 'mart'},
}
map_slugs[0x0A] = {
    0x00: {'location': 'mauville-city', 'area': 'gym'},
    0x01: {'location': 'mauville-city', 'area': 'bike-shop'},
    0x02: {'location': 'mauville-city', 'area': 'house-1'},
    0x03: {'location': 'mauville-city', 'area': 'game-corner'},
    0x04: {'location': 'mauville-city', 'area': 'house-2'},
    0x05: {'location': 'mauville-city', 'area': 'pokemon-center/1f'},
    0x06: {'location': 'mauville-city', 'area': 'pokemon-center/2f'},
    0x07: {'location': 'mauville-city', 'area': 'mart'},
}
map_slugs[0x0B] = {
    0x00: {'location': 'rustboro-city', 'area': 'devon-corp/1f'},
    0x01: {'location': 'rustboro-city', 'area': 'devon-corp/2f'},
    0x02: {'location': 'rustboro-city', 'area': 'devon-corp/3f'},
    0x03: {'location': 'rustboro-city', 'area': 'gym'},
    0x04: {'location': 'rustboro-city', 'area': 'pokemon-school'},
    0x05: {'location': 'rustboro-city', 'area': 'pokemon-center/1f'},
    0x06: {'location': 'rustboro-city', 'area': 'pokemon-center/2f'},
    0x07: {'location': 'rustboro-city', 'area': 'mart'},
    0x08: {'location': 'rustboro-city', 'area': 'flat-1/1f'},
    0x09: {'location': 'rustboro-city', 'area': 'flat-1/2f'},
    0x0A: {'location': 'rustboro-city', 'area': 'house-1'},
    0x0B: {'location': 'rustboro-city', 'area': 'cutters-house'},
    0x0C: {'location': 'rustboro-city', 'area': 'house-2'},
    0x0D: {'location': 'rustboro-city', 'area': 'flat-2/1f'},
    0x0E: {'location': 'rustboro-city', 'area': 'flat-2/2f'},
    0x0F: {'location': 'rustboro-city', 'area': 'flat-2/3f'},
    0x10: {'location': 'rustboro-city', 'area': 'house-3'},
}
map_slugs[0x0C] = {
    0x00: {'location': 'fortree-city', 'area': 'house-1'},
    0x01: {'location': 'fortree-city', 'area': 'gym'},
    0x02: {'location': 'fortree-city', 'area': 'pokemon-center/1f'},
    0x03: {'location': 'fortree-city', 'area': 'pokemon-center/2f'},
    0x04: {'location': 'fortree-city', 'area': 'mart'},
    0x05: {'location': 'fortree-city', 'area': 'house-2'},
    0x06: {'location': 'fortree-city', 'area': 'house-3'},
    0x07: {'location': 'fortree-city', 'area': 'house-4'},
    0x08: {'location': 'fortree-city', 'area': 'house-5'},
    0x09: {'location': 'fortree-city', 'area': 'decoration-shop'},
}
map_slugs[0x0D] = {
    0x00: {'location': 'lilycove-city', 'area': 'cove-lily-motel/1f'},
    0x01: {'location': 'lilycove-city', 'area': 'cove-lily-motel/2f'},
    0x02: {'location': 'lilycove-city', 'area': 'lilycove-museum/1f'},
    0x03: {'location': 'lilycove-city', 'area': 'lilycove-museum/2f'},
    0x04: {'location': 'lilycove-city', 'area': 'contest-lobby'},
    0x05: {'location': 'lilycove-city', 'area': 'contest-hall'},
    0x06: {'location': 'lilycove-city', 'area': 'pokemon-center/1f'},
    0x07: {'location': 'lilycove-city', 'area': 'pokemon-center/2f'},
    0x08: {'location': 'lilycove-city', 'area': 'unused-mart'},
    0x09: {'location': 'lilycove-city', 'area': 'pokemon-trainer-fan-club'},
    0x0A: {'location': 'lilycove-city', 'area': 'harbor'},
    0x0B: {'location': 'lilycove-city', 'area': 'move-deleters-house'},
    0x0C: {'location': 'lilycove-city', 'area': 'house-1'},
    0x0D: {'location': 'lilycove-city', 'area': 'house-2'},
    0x0E: {'location': 'lilycove-city', 'area': 'house-3'},
    0x0F: {'location': 'lilycove-city', 'area': 'house-4'},
    0x10: {'location': 'lilycove-city', 'area': 'department-store/1f'},
    0x11: {'location': 'lilycove-city', 'area': 'department-store/2f'},
    0x12: {'location': 'lilycove-city', 'area': 'department-store/3f'},
    0x13: {'location': 'lilycove-city', 'area': 'department-store/4f'},
    0x14: {'location': 'lilycove-city', 'area': 'department-store/5f'},
    0x15: {'location': 'lilycove-city', 'area': 'department-store/roof'},
    0x16: {'location': 'lilycove-city', 'area': 'department-store/elevator'},
}
map_slugs[0x0E] = {
    0x00: {'location': 'mossdeep-city', 'area': 'gym'},
    0x01: {'location': 'mossdeep-city', 'area': 'house-1'},
    0x02: {'location': 'mossdeep-city', 'area': 'house-2'},
    0x03: {'location': 'mossdeep-city', 'area': 'pokemon-center/1f'},
    0x04: {'location': 'mossdeep-city', 'area': 'pokemon-center/2f'},
    0x05: {'location': 'mossdeep-city', 'area': 'mart'},
    0x06: {'location': 'mossdeep-city', 'area': 'house-3'},
    0x07: {'location': 'mossdeep-city', 'area': 'stevens-house'},
    0x08: {'location': 'mossdeep-city', 'area': 'house-4'},
    0x09: {'location': 'mossdeep-city', 'area': 'space-center/1f'},
    0x0A: {'location': 'mossdeep-city', 'area': 'space-center/2f'},
    0x0B: {'location': 'mossdeep-city', 'area': 'game-corner/1f'},
    0x0C: {'location': 'mossdeep-city', 'area': 'game-corner/b1f'},
}
map_slugs[0x0F] = {
    0x00: {'location': 'sootopolis-city', 'area': 'gym/1f'},
    0x01: {'location': 'sootopolis-city', 'area': 'gym/b1f'},
    0x02: {'location': 'sootopolis-city', 'area': 'pokemon-center/1f'},
    0x03: {'location': 'sootopolis-city', 'area': 'pokemon-center/2f'},
    0x04: {'location': 'sootopolis-city', 'area': 'mart'},
    0x05: {'location': 'sootopolis-city', 'area': 'house-1'},
    0x06: {'location': 'sootopolis-city', 'area': 'house-2'},
    0x07: {'location': 'sootopolis-city', 'area': 'house-3'},
    0x08: {'location': 'sootopolis-city', 'area': 'house-4'},
    0x09: {'location': 'sootopolis-city', 'area': 'house-5'},
    0x0A: {'location': 'sootopolis-city', 'area': 'house-6'},
    0x0B: {'location': 'sootopolis-city', 'area': 'house-7'},
    0x0C: {'location': 'sootopolis-city', 'area': 'lotad-and-seedot-house'},
    0x0D: {'location': 'sootopolis-city', 'area': 'mystery-events-house/1f'},
    0x0E: {'location': 'sootopolis-city', 'area': 'mystery-events-house/b1f'},
}
map_slugs[0x10] = {
    0x00: {'location': 'ever-grande-city', 'area': 'sidneys-room'},
    0x01: {'location': 'ever-grande-city', 'area': 'phoebes-room'},
    0x02: {'location': 'ever-grande-city', 'area': 'glacias-room'},
    0x03: {'location': 'ever-grande-city', 'area': 'drakes-room'},
    0x04: {'location': 'ever-grande-city', 'area': 'champions-room'},
    0x05: {'location': 'ever-grande-city', 'area': 'hall-1'},
    0x06: {'location': 'ever-grande-city', 'area': 'hall-2'},
    0x07: {'location': 'ever-grande-city', 'area': 'hall-3'},
    0x08: {'location': 'ever-grande-city', 'area': 'hall-4'},
    0x09: {'location': 'ever-grande-city', 'area': 'hall-5'},
    0x0A: {'location': 'ever-grande-city', 'area': 'pokemon-league/1f'},
    0x0B: {'location': 'ever-grande-city', 'area': 'hall-of-fame'},
    0x0C: {'location': 'ever-grande-city', 'area': 'pokemon-center/1f'},
    0x0D: {'location': 'ever-grande-city', 'area': 'pokemon-center/2f'},
    0x0E: {'location': 'ever-grande-city', 'area': 'pokemon-league/2f'},
}
map_slugs[0x11] = {
    0x00: {'location': 'hoenn-route-104', 'area': 'mr-brineys-house'},
    0x01: {'location': 'hoenn-route-104', 'area': 'pretty-petal-flower-shop'},
}
map_slugs[0x12] = {
    0x00: {'location': 'hoenn-route-111', 'area': 'winstrate-familys-house'},
    0x01: {'location': 'hoenn-route-111', 'area': 'old-ladys-rest-stop'},
}
map_slugs[0x13] = {
    0x00: {'location': 'hoenn-route-112', 'area': 'cable-car-station'},
    0x01: {'location': 'mt-chimney', 'area': 'cable-car-station'},
}
map_slugs[0x14] = {
    0x00: {'location': 'hoenn-route-114', 'area': 'fossil-maniacs-house'},
    0x01: {'location': 'hoenn-route-114', 'area': 'fossil-maniacs-tunnel'},
    0x02: {'location': 'hoenn-route-114', 'area': 'lanettes-house'},
}
map_slugs[0x15] = {
    0x00: {'location': 'hoenn-route-116', 'area': 'tunnelers-rest-house'},
}
map_slugs[0x16] = {
    0x00: {'location': 'hoenn-route-117', 'area': 'pokemon-day-care'},
}
map_slugs[0x17] = {
    0x00: {'location': 'hoenn-route-121', 'area': 'safari-zone-entrance'},
}
map_slugs[0x18] = {
    0x00: {'location': 'meteor-falls', 'area': '1f/1r'},
    0x01: {'location': 'meteor-falls', 'area': '1f/2r'},
    0x02: {'location': 'meteor-falls', 'area': 'b1f/1r'},
    0x03: {'location': 'meteor-falls', 'area': 'b1f/2r'},
    0x04: {'location': 'rusturf-tunnel', 'area': 'whole-area'},
    0x05: {'location': 'underwater', 'area': 'sootopolis-city'},
    0x06: {'location': 'desert-ruins', 'area': 'whole-area'},
    0x07: {'location': 'granite-cave', 'area': '1f'},
    0x08: {'location': 'granite-cave', 'area': 'b1f'},
    0x09: {'location': 'granite-cave', 'area': 'b2f'},
    0x0A: {'location': 'granite-cave', 'area': 'stevens-room'},
    0x0B: {'location': 'petalburg-woods', 'area': 'whole-area'},
    0x0C: {'location': 'mt-chimney', 'area': 'whole-area'},
    0x0D: {'location': 'jagged-pass', 'area': 'whole-area'},
    0x0E: {'location': 'fiery-path', 'area': 'whole-area'},
    0x0F: {'location': 'mt-pyre', 'area': '1f'},
    0x10: {'location': 'mt-pyre', 'area': '2f'},
    0x11: {'location': 'mt-pyre', 'area': '3f'},
    0x12: {'location': 'mt-pyre', 'area': '4f'},
    0x13: {'location': 'mt-pyre', 'area': '5f'},
    0x14: {'location': 'mt-pyre', 'area': '6f'},
    0x15: {'location': 'mt-pyre', 'area': 'exterior'},
    0x16: {'location': 'mt-pyre', 'area': 'summit'},
    0x17: {'location': 'aqua-hideout', 'area': '1f'},
    0x18: {'location': 'aqua-hideout', 'area': 'b1f'},
    0x19: {'location': 'aqua-hideout', 'area': 'b2f'},
    0x1A: {'location': 'underwater', 'area': 'seafloor-cavern'},
    0x1B: {'location': 'seafloor-cavern', 'area': 'entrance'},
    0x1C: {'location': 'seafloor-cavern', 'area': 'room-1'},
    0x1D: {'location': 'seafloor-cavern', 'area': 'room-2'},
    0x1E: {'location': 'seafloor-cavern', 'area': 'room-3'},
    0x1F: {'location': 'seafloor-cavern', 'area': 'room-4'},
    0x20: {'location': 'seafloor-cavern', 'area': 'room-5'},
    0x21: {'location': 'seafloor-cavern', 'area': 'room-6'},
    0x22: {'location': 'seafloor-cavern', 'area': 'room-7'},
    0x23: {'location': 'seafloor-cavern', 'area': 'room-8'},
    0x24: {'location': 'seafloor-cavern', 'area': 'room-9'},
    0x25: {'location': 'cave-of-origin', 'area': 'entrance'},
    0x26: {'location': 'cave-of-origin', 'area': '1f'},
    # 0x27: {'location': 'cave-of-origin', 'area': 'unused-ruby-sapphire-map-1'},
    # 0x28: {'location': 'cave-of-origin', 'area': 'unused-ruby-sapphire-map-2'},
    # 0x29: {'location': 'cave-of-origin', 'area': 'unused-ruby-sapphire-map-3'},
    0x2A: {'location': 'cave-of-origin', 'area': 'b1f'},
    0x2B: {'location': 'victory-road', 'area': '1f'},
    0x2C: {'location': 'victory-road', 'area': 'b1f'},
    0x2D: {'location': 'victory-road', 'area': 'b2f'},
    0x2E: {'location': 'shoal-cave', 'area': 'low-tide-entrance-room'},
    0x2F: {'location': 'shoal-cave', 'area': 'low-tide-inner-room'},
    0x30: {'location': 'shoal-cave', 'area': 'low-tide-stairs-room'},
    0x31: {'location': 'shoal-cave', 'area': 'low-tide-lower-room'},
    0x32: {'location': 'shoal-cave', 'area': 'high-tide-entrance-room'},
    0x33: {'location': 'shoal-cave', 'area': 'high-tide-inner-room'},
    0x34: {'location': 'new-mauville', 'area': 'entrance'},
    0x35: {'location': 'new-mauville', 'area': 'inside'},
    0x36: {'location': 'abandoned-ship', 'area': 'deck'},
    0x37: {'location': 'abandoned-ship', 'area': 'corridors/1f'},
    0x38: {'location': 'abandoned-ship', 'area': 'rooms/1f'},
    0x39: {'location': 'abandoned-ship', 'area': 'corridors/b1f'},
    0x3A: {'location': 'abandoned-ship', 'area': 'rooms/b1f'},
    0x3B: {'location': 'abandoned-ship', 'area': 'rooms-2/b1f'},
    0x3C: {'location': 'abandoned-ship', 'area': 'underwater-1'},
    0x3D: {'location': 'abandoned-ship', 'area': 'room/b1f'},
    0x3E: {'location': 'abandoned-ship', 'area': 'rooms-2/1f'},
    0x3F: {'location': 'abandoned-ship', 'area': 'captains-office'},
    0x40: {'location': 'abandoned-ship', 'area': 'underwater-2'},
    0x41: {'location': 'abandoned-ship', 'area': 'hidden-floor-corridors'},
    0x42: {'location': 'abandoned-ship', 'area': 'hidden-floor-rooms'},
    0x43: {'location': 'island-cave', 'area': 'whole-area'},
    0x44: {'location': 'ancient-tomb', 'area': 'whole-area'},
    0x45: {'location': 'underwater', 'area': 'route-134'},
    0x46: {'location': 'underwater', 'area': 'sealed-chamber'},
    0x47: {'location': 'sealed-chamber', 'area': 'outer-room'},
    0x48: {'location': 'sealed-chamber', 'area': 'inner-room'},
    0x49: {'location': 'scorched-slab', 'area': 'whole-area'},
    # 0x4A: {'location': 'aqua-hideout', 'area': 'unused-ruby-map-1'},
    # 0x4B: {'location': 'aqua-hideout', 'area': 'unused-ruby-map-2'},
    # 0x4C: {'location': 'aqua-hideout', 'area': 'unused-ruby-map-3'},
    0x4D: {'location': 'sky-pillar', 'area': 'entrance'},
    0x4E: {'location': 'sky-pillar', 'area': 'outside'},
    0x4F: {'location': 'sky-pillar', 'area': '1f'},
    0x50: {'location': 'sky-pillar', 'area': '2f'},
    0x51: {'location': 'sky-pillar', 'area': '3f'},
    0x52: {'location': 'sky-pillar', 'area': '4f'},
    0x53: {'location': 'shoal-cave', 'area': 'low-tide-ice-room'},
    0x54: {'location': 'sky-pillar', 'area': '5f'},
    0x55: {'location': 'sky-pillar', 'area': 'top'},
    0x56: {'location': 'magma-hideout', 'area': '1f'},
    0x57: {'location': 'magma-hideout', 'area': '2f/1r'},
    0x58: {'location': 'magma-hideout', 'area': '2f/2r'},
    0x59: {'location': 'magma-hideout', 'area': '3f/1r'},
    0x5A: {'location': 'magma-hideout', 'area': '3f/2r'},
    0x5B: {'location': 'magma-hideout', 'area': '4f'},
    0x5C: {'location': 'magma-hideout', 'area': '3f/3r'},
    0x5D: {'location': 'magma-hideout', 'area': '2f/3r'},
    0x5E: {'location': 'mirage-tower', 'area': '1f'},
    0x5F: {'location': 'mirage-tower', 'area': '2f'},
    0x60: {'location': 'mirage-tower', 'area': '3f'},
    0x61: {'location': 'mirage-tower', 'area': '4f'},
    0x62: {'location': 'desert-underpass', 'area': 'whole-area'},
    0x63: {'location': 'artisan-cave', 'area': 'b1f'},
    0x64: {'location': 'artisan-cave', 'area': '1f'},
    0x65: {'location': 'underwater', 'area': 'marine-cave'},
    0x66: {'location': 'marine-cave', 'area': 'entrance'},
    0x67: {'location': 'marine-cave', 'area': 'end'},
    0x68: {'location': 'terra-cave', 'area': 'entrance'},
    0x69: {'location': 'terra-cave', 'area': 'end'},
    0x6A: {'location': 'altering-cave', 'area': 'whole-area'},
    0x6B: {'location': 'meteor-falls', 'area': 'stevens-cave'},
}
map_slugs[0x19] = {
    0x00: {'location': 'secret-base', 'area': 'red-cave-1'},
    0x01: {'location': 'secret-base', 'area': 'brown-cave-1'},
    0x02: {'location': 'secret-base', 'area': 'blue-cave-1'},
    0x03: {'location': 'secret-base', 'area': 'yellow-cave-1'},
    0x04: {'location': 'secret-base', 'area': 'tree-1'},
    0x05: {'location': 'secret-base', 'area': 'shrub-1'},
    0x06: {'location': 'secret-base', 'area': 'red-cave-2'},
    0x07: {'location': 'secret-base', 'area': 'brown-cave-2'},
    0x08: {'location': 'secret-base', 'area': 'blue-cave-2'},
    0x09: {'location': 'secret-base', 'area': 'yellow-cave-2'},
    0x0A: {'location': 'secret-base', 'area': 'tree-2'},
    0x0B: {'location': 'secret-base', 'area': 'shrub-2'},
    0x0C: {'location': 'secret-base', 'area': 'red-cave-3'},
    0x0D: {'location': 'secret-base', 'area': 'brown-cave-3'},
    0x0E: {'location': 'secret-base', 'area': 'blue-cave-3'},
    0x0F: {'location': 'secret-base', 'area': 'yellow-cave-3'},
    0x10: {'location': 'secret-base', 'area': 'tree-3'},
    0x11: {'location': 'secret-base', 'area': 'shrub-3'},
    0x12: {'location': 'secret-base', 'area': 'red-cave-4'},
    0x13: {'location': 'secret-base', 'area': 'brown-cave-4'},
    0x14: {'location': 'secret-base', 'area': 'blue-cave-4'},
    0x15: {'location': 'secret-base', 'area': 'yellow-cave-4'},
    0x16: {'location': 'secret-base', 'area': 'tree-4'},
    0x17: {'location': 'secret-base', 'area': 'shrub-4'},
    # 0x18: {'location': 'battle-colosseum', 'area': '2p'},
    # 0x19: {'location': 'trade-center', 'area': 'whole-area'},
    # 0x1A: {'location': 'record-corner', 'area': 'whole-area'},
    # 0x1B: {'location': 'battle-colosseum', 'area': '4p'},
    # 0x1C: {'location': 'contest-hall', 'area': 'whole-area'},
    # 0x1D: {'location': 'unknown-link-contest-room', 'area': '25/29'},
    # 0x1E: {'location': 'unknown-link-contest-room', 'area': '25/30'},
    # 0x1F: {'location': 'unknown-link-contest-room', 'area': '25/31'},
    # 0x20: {'location': 'unknown-link-contest-room', 'area': '25/32'},
    # 0x21: {'location': 'unknown-link-contest-room', 'area': '25/33'},
    # 0x22: {'location': 'unknown-link-contest-room', 'area': '25/34'},
    # 0x23: {'location': 'contest-hall-beauty', 'area': 'whole-area'},
    # 0x24: {'location': 'contest-hall-tough', 'area': 'whole-area'},
    # 0x25: {'location': 'contest-hall-cool', 'area': 'whole-area'},
    # 0x26: {'location': 'contest-hall-smart', 'area': 'whole-area'},
    # 0x27: {'location': 'contest-hall-cute', 'area': 'whole-area'},
    # 0x28: {'location': 'inside-of-truck', 'area': 'whole-area'},
    0x29: {'location': 'ss-tidal-corridor', 'area': 'whole-area'},
    0x2A: {'location': 'ss-tidal-lower-deck', 'area': 'whole-area'},
    0x2B: {'location': 'ss-tidal-rooms', 'area': 'whole-area'},
    0x2C: {'location': 'battle-pyramid-square-01', 'area': 'whole-area'},
    0x2D: {'location': 'battle-pyramid-square-02', 'area': 'whole-area'},
    0x2E: {'location': 'battle-pyramid-square-03', 'area': 'whole-area'},
    0x2F: {'location': 'battle-pyramid-square-04', 'area': 'whole-area'},
    0x30: {'location': 'battle-pyramid-square-05', 'area': 'whole-area'},
    0x31: {'location': 'battle-pyramid-square-06', 'area': 'whole-area'},
    0x32: {'location': 'battle-pyramid-square-07', 'area': 'whole-area'},
    0x33: {'location': 'battle-pyramid-square-08', 'area': 'whole-area'},
    0x34: {'location': 'battle-pyramid-square-09', 'area': 'whole-area'},
    0x35: {'location': 'battle-pyramid-square-10', 'area': 'whole-area'},
    0x36: {'location': 'battle-pyramid-square-11', 'area': 'whole-area'},
    0x37: {'location': 'battle-pyramid-square-12', 'area': 'whole-area'},
    0x38: {'location': 'battle-pyramid-square-13', 'area': 'whole-area'},
    0x39: {'location': 'battle-pyramid-square-14', 'area': 'whole-area'},
    0x3A: {'location': 'battle-pyramid-square-15', 'area': 'whole-area'},
    0x3B: {'location': 'battle-pyramid-square-16', 'area': 'whole-area'},
    0x3C: {'location': 'union-room', 'area': 'whole-area'},
}
map_slugs[0x1A] = {
    0x00: {'location': 'safari-zone', 'area': 'northwest'},
    0x01: {'location': 'safari-zone', 'area': 'north'},
    0x02: {'location': 'safari-zone', 'area': 'southwest'},
    0x03: {'location': 'safari-zone', 'area': 'south'},
    0x04: {'location': 'battle-frontier', 'area': 'outside-west'},
    0x05: {'location': 'battle-frontier', 'area': 'battle-tower-lobby'},
    0x06: {'location': 'battle-frontier', 'area': 'battle-tower-elevator'},
    0x07: {'location': 'battle-frontier', 'area': 'battle-tower-corridor'},
    0x08: {'location': 'battle-frontier', 'area': 'battle-tower-battle-room'},
    0x09: {'location': 'southern-island', 'area': 'exterior'},
    0x0A: {'location': 'southern-island', 'area': 'interior'},
    0x0B: {'location': 'safari-zone', 'area': 'rest-house'},
    0x0C: {'location': 'safari-zone', 'area': 'northeast'},
    0x0D: {'location': 'safari-zone', 'area': 'southeast'},
    0x0E: {'location': 'battle-frontier', 'area': 'outside-east'},
    0x0F: {'location': 'battle-frontier', 'area': 'battle-tower-multi-partner-room'},
    0x10: {'location': 'battle-frontier', 'area': 'battle-tower-multi-corridor'},
    0x11: {'location': 'battle-frontier', 'area': 'battle-tower-multi-battle-room'},
    0x12: {'location': 'battle-frontier', 'area': 'battle-dome-lobby'},
    0x13: {'location': 'battle-frontier', 'area': 'battle-dome-corridor'},
    0x14: {'location': 'battle-frontier', 'area': 'battle-dome-pre-battle-room'},
    0x15: {'location': 'battle-frontier', 'area': 'battle-dome-battle-room'},
    0x16: {'location': 'battle-frontier', 'area': 'battle-palace-lobby'},
    0x17: {'location': 'battle-frontier', 'area': 'battle-palace-corridor'},
    0x18: {'location': 'battle-frontier', 'area': 'battle-palace-battle-room'},
    0x19: {'location': 'battle-frontier', 'area': 'battle-pyramid-lobby'},
    0x1A: {'location': 'battle-frontier', 'area': 'battle-pyramid-floor'},
    0x1B: {'location': 'battle-frontier', 'area': 'battle-pyramid-top'},
    0x1C: {'location': 'battle-frontier', 'area': 'battle-arena-lobby'},
    0x1D: {'location': 'battle-frontier', 'area': 'battle-arena-corridor'},
    0x1E: {'location': 'battle-frontier', 'area': 'battle-arena-battle-room'},
    0x1F: {'location': 'battle-frontier', 'area': 'battle-factory-lobby'},
    0x20: {'location': 'battle-frontier', 'area': 'battle-factory-pre-battle-room'},
    0x21: {'location': 'battle-frontier', 'area': 'battle-factory-battle-room'},
    0x22: {'location': 'battle-frontier', 'area': 'battle-pike-lobby'},
    0x23: {'location': 'battle-frontier', 'area': 'battle-pike-corridor'},
    0x24: {'location': 'battle-frontier', 'area': 'battle-pike-three-path-room'},
    0x25: {'location': 'battle-frontier', 'area': 'battle-pike-room-normal'},
    0x26: {'location': 'battle-frontier', 'area': 'battle-pike-room-final'},
    0x27: {'location': 'battle-frontier', 'area': 'battle-pike-room-wild-mons'},
    0x28: {'location': 'battle-frontier', 'area': 'ranking-hall'},
    0x29: {'location': 'battle-frontier', 'area': 'lounge-1'},
    0x2A: {'location': 'battle-frontier', 'area': 'exchange-service-corner'},
    0x2B: {'location': 'battle-frontier', 'area': 'lounge-2'},
    0x2C: {'location': 'battle-frontier', 'area': 'lounge-3'},
    0x2D: {'location': 'battle-frontier', 'area': 'lounge-4'},
    0x2E: {'location': 'battle-frontier', 'area': 'scotts-house'},
    0x2F: {'location': 'battle-frontier', 'area': 'lounge-5'},
    0x30: {'location': 'battle-frontier', 'area': 'lounge-6'},
    0x31: {'location': 'battle-frontier', 'area': 'lounge-7'},
    0x32: {'location': 'battle-frontier', 'area': 'reception-gate'},
    0x33: {'location': 'battle-frontier', 'area': 'lounge-8'},
    0x34: {'location': 'battle-frontier', 'area': 'lounge-9'},
    0x35: {'location': 'battle-frontier', 'area': 'pokemon-center/1f'},
    0x36: {'location': 'battle-frontier', 'area': 'pokemon-center/2f'},
    0x37: {'location': 'battle-frontier', 'area': 'mart'},
    0x38: {'location': 'faraway-island', 'area': 'entrance'},
    0x39: {'location': 'faraway-island', 'area': 'interior'},
    0x3A: {'location': 'birth-island', 'area': 'exterior'},
    0x3B: {'location': 'birth-island', 'area': 'harbor'},
    0x3C: {'location': 'trainer-hill', 'area': 'entrance'},
    0x3D: {'location': 'trainer-hill', 'area': '1f'},
    0x3E: {'location': 'trainer-hill', 'area': '2f'},
    0x3F: {'location': 'trainer-hill', 'area': '3f'},
    0x40: {'location': 'trainer-hill', 'area': '4f'},
    0x41: {'location': 'trainer-hill', 'area': 'roof'},
    0x42: {'location': 'navel-rock', 'area': 'exterior'},
    0x43: {'location': 'navel-rock', 'area': 'harbor'},
    0x44: {'location': 'navel-rock', 'area': 'entrance'},
    0x45: {'location': 'navel-rock', 'area': 'b1f'},
    0x46: {'location': 'navel-rock', 'area': 'fork'},
    0x47: {'location': 'navel-rock', 'area': 'up-1'},
    0x48: {'location': 'navel-rock', 'area': 'up-2'},
    0x49: {'location': 'navel-rock', 'area': 'up-3'},
    0x4A: {'location': 'navel-rock', 'area': 'up-4'},
    0x4B: {'location': 'navel-rock', 'area': 'top'},
    0x4C: {'location': 'navel-rock', 'area': 'down-01'},
    0x4D: {'location': 'navel-rock', 'area': 'down-02'},
    0x4E: {'location': 'navel-rock', 'area': 'down-03'},
    0x4F: {'location': 'navel-rock', 'area': 'down-04'},
    0x50: {'location': 'navel-rock', 'area': 'down-05'},
    0x51: {'location': 'navel-rock', 'area': 'down-06'},
    0x52: {'location': 'navel-rock', 'area': 'down-07'},
    0x53: {'location': 'navel-rock', 'area': 'down-08'},
    0x54: {'location': 'navel-rock', 'area': 'down-09'},
    0x55: {'location': 'navel-rock', 'area': 'down-10'},
    0x56: {'location': 'navel-rock', 'area': 'down-11'},
    0x57: {'location': 'navel-rock', 'area': 'bottom'},
    0x58: {'location': 'trainer-hill', 'area': 'elevator'},
}
map_slugs[0x1B] = {
    # 0x00: {'location': 'hoenn-route-104', 'area': 'prototype'},
    # 0x01: {'location': 'hoenn-route-104', 'area': 'prototype-pretty-petal-flower-shop'},
}
map_slugs[0x1C] = {
    0x00: {'location': 'hoenn-route-109', 'area': 'seashore-house'},
}
map_slugs[0x1D] = {
    0x00: {'location': 'hoenn-route-110', 'area': 'trick-house-entrance'},
    0x01: {'location': 'hoenn-route-110', 'area': 'trick-house-end'},
    0x02: {'location': 'hoenn-route-110', 'area': 'trick-house-corridor'},
    0x03: {'location': 'hoenn-route-110', 'area': 'trick-house-puzzle-1'},
    0x04: {'location': 'hoenn-route-110', 'area': 'trick-house-puzzle-2'},
    0x05: {'location': 'hoenn-route-110', 'area': 'trick-house-puzzle-3'},
    0x06: {'location': 'hoenn-route-110', 'area': 'trick-house-puzzle-4'},
    0x07: {'location': 'hoenn-route-110', 'area': 'trick-house-puzzle-5'},
    0x08: {'location': 'hoenn-route-110', 'area': 'trick-house-puzzle-6'},
    0x09: {'location': 'hoenn-route-110', 'area': 'trick-house-puzzle-7'},
    0x0A: {'location': 'hoenn-route-110', 'area': 'trick-house-puzzle-8'},
    0x0B: {'location': 'hoenn-route-110', 'area': 'seaside-cycling-road-north-entrance'},
    0x0C: {'location': 'hoenn-route-110', 'area': 'seaside-cycling-road-south-entrance'},
}
map_slugs[0x1E] = {
    0x00: {'location': 'hoenn-route-113', 'area': 'glass-workshop'},
}
map_slugs[0x1F] = {
    0x00: {'location': 'hoenn-route-123', 'area': 'berry-masters-house'},
}
map_slugs[0x20] = {
    0x00: {'location': 'hoenn-route-119', 'area': 'weather-institute/1f'},
    0x01: {'location': 'hoenn-route-119', 'area': 'weather-institute/2f'},
    0x02: {'location': 'hoenn-route-119', 'area': 'house'},
}
map_slugs[0x21] = {
    0x00: {'location': 'hoenn-route-124', 'area': 'diving-treasure-hunters-house'},
}
