map_slugs = {}
map_slugs[0x00] = {
    # 0x00: {'location': 'battle-colosseum', 'area': '2p'},
    # 0x01: {'location': 'trade-center', 'area': 'whole-area'},
    # 0x02: {'location': 'record-center', 'area': 'whole-area'},
    # 0x03: {'location': 'battle-colosseum', 'area': '4p'},
    # 0x04: {'location': 'union-room', 'area': 'whole-area'},
}
map_slugs[0x01] = {
    0x00: {'location': 'viridian-forest', 'area': 'whole-area'},
    0x01: {'location': 'mt-moon', 'area': '1f'},
    0x02: {'location': 'mt-moon', 'area': 'b1f'},
    0x03: {'location': 'mt-moon', 'area': 'b2f'},
    0x04: {'location': 'ss-anne', 'area': 'exterior'},
    0x05: {'location': 'ss-anne', 'area': '1f/corridor'},
    0x06: {'location': 'ss-anne', 'area': '2f/corridor'},
    0x07: {'location': 'ss-anne', 'area': '3f/corridor'},
    0x08: {'location': 'ss-anne', 'area': 'b1f/corridor'},
    0x09: {'location': 'ss-anne', 'area': 'deck'},
    0x0A: {'location': 'ss-anne', 'area': 'kitchen'},
    0x0B: {'location': 'ss-anne', 'area': 'captains-office'},
    0x0C: {'location': 'ss-anne', 'area': '1f/room-1'},
    0x0D: {'location': 'ss-anne', 'area': '1f/room-2'},
    0x0E: {'location': 'ss-anne', 'area': '1f/room-3'},
    0x0F: {'location': 'ss-anne', 'area': '1f/room-4'},
    0x10: {'location': 'ss-anne', 'area': '1f/room-5'},
    0x11: {'location': 'ss-anne', 'area': '1f/room-7'},
    0x12: {'location': 'ss-anne', 'area': '2f/room-1'},
    0x13: {'location': 'ss-anne', 'area': '2f/room-2'},
    0x14: {'location': 'ss-anne', 'area': '2f/room-3'},
    0x15: {'location': 'ss-anne', 'area': '2f/room-4'},
    0x16: {'location': 'ss-anne', 'area': '2f/room-5'},
    0x17: {'location': 'ss-anne', 'area': '2f/room-6'},
    0x18: {'location': 'ss-anne', 'area': 'b1f/room-1'},
    0x19: {'location': 'ss-anne', 'area': 'b1f/room-2'},
    0x1A: {'location': 'ss-anne', 'area': 'b1f/room-3'},
    0x1B: {'location': 'ss-anne', 'area': 'b1f/room-4'},
    0x1C: {'location': 'ss-anne', 'area': 'b1f/room-5'},
    0x1D: {'location': 'ss-anne', 'area': '1f/room-6'},
    0x1E: {'location': 'underground-path', 'area': 'north-entrance'},
    0x1F: {'location': 'underground-path', 'area': 'north-south-tunnel'},
    0x20: {'location': 'underground-path', 'area': 'south-entrance'},
    0x21: {'location': 'underground-path', 'area': 'west-entrance'},
    0x22: {'location': 'underground-path', 'area': 'east-west-tunnel'},
    0x23: {'location': 'underground-path', 'area': 'east-entrance'},
    0x24: {'location': 'digletts-cave', 'area': 'north-entrance'},
    0x25: {'location': 'digletts-cave', 'area': 'b1f'},
    0x26: {'location': 'digletts-cave', 'area': 'south-entrance'},
    0x27: {'location': 'victory-road', 'area': '1f'},
    0x28: {'location': 'victory-road', 'area': '2f'},
    0x29: {'location': 'victory-road', 'area': '3f'},
    0x2A: {'location': 'rocket-hideout', 'area': 'b1f'},
    0x2B: {'location': 'rocket-hideout', 'area': 'b2f'},
    0x2C: {'location': 'rocket-hideout', 'area': 'b3f'},
    0x2D: {'location': 'rocket-hideout', 'area': 'b4f'},
    0x2E: {'location': 'rocket-hideout', 'area': 'elevator'},
    0x2F: {'location': 'silph-co', 'area': '1f'},
    0x30: {'location': 'silph-co', 'area': '2f'},
    0x31: {'location': 'silph-co', 'area': '3f'},
    0x32: {'location': 'silph-co', 'area': '4f'},
    0x33: {'location': 'silph-co', 'area': '5f'},
    0x34: {'location': 'silph-co', 'area': '6f'},
    0x35: {'location': 'silph-co', 'area': '7f'},
    0x36: {'location': 'silph-co', 'area': '8f'},
    0x37: {'location': 'silph-co', 'area': '9f'},
    0x38: {'location': 'silph-co', 'area': '10f'},
    0x39: {'location': 'silph-co', 'area': '11f'},
    0x3A: {'location': 'silph-co', 'area': 'elevator'},
    0x3B: {'location': 'pokemon-mansion', 'area': '1f'},
    0x3C: {'location': 'pokemon-mansion', 'area': '2f'},
    0x3D: {'location': 'pokemon-mansion', 'area': '3f'},
    0x3E: {'location': 'pokemon-mansion', 'area': 'b1f'},
    0x3F: {'location': 'safari-zone', 'area': 'center'},
    0x40: {'location': 'safari-zone', 'area': 'east'},
    0x41: {'location': 'safari-zone', 'area': 'north'},
    0x42: {'location': 'safari-zone', 'area': 'west'},
    0x43: {'location': 'safari-zone', 'area': 'center/rest-house'},
    0x44: {'location': 'safari-zone', 'area': 'east/rest-house'},
    0x45: {'location': 'safari-zone', 'area': 'north/rest-house'},
    0x46: {'location': 'safari-zone', 'area': 'west/rest-house'},
    0x47: {'location': 'safari-zone', 'area': 'secret-house'},
    0x48: {'location': 'cerulean-cave', 'area': '1f'},
    0x49: {'location': 'cerulean-cave', 'area': '2f'},
    0x4A: {'location': 'cerulean-cave', 'area': 'b1f'},
    0x4B: {'location': 'pokemon-league', 'area': 'loreleis-room'},
    0x4C: {'location': 'pokemon-league', 'area': 'brunos-room'},
    0x4D: {'location': 'pokemon-league', 'area': 'agathas-room'},
    0x4E: {'location': 'pokemon-league', 'area': 'lances-room'},
    0x4F: {'location': 'pokemon-league', 'area': 'champions-room'},
    0x50: {'location': 'pokemon-league', 'area': 'hall-of-fame'},
    0x51: {'location': 'rock-tunnel', 'area': '1f'},
    0x52: {'location': 'rock-tunnel', 'area': 'b1f'},
    0x53: {'location': 'seafoam-islands', 'area': '1f'},
    0x54: {'location': 'seafoam-islands', 'area': 'b1f'},
    0x55: {'location': 'seafoam-islands', 'area': 'b2f'},
    0x56: {'location': 'seafoam-islands', 'area': 'b3f'},
    0x57: {'location': 'seafoam-islands', 'area': 'b4f'},
    0x58: {'location': 'pokemon-tower', 'area': '1f'},
    0x59: {'location': 'pokemon-tower', 'area': '2f'},
    0x5A: {'location': 'pokemon-tower', 'area': '3f'},
    0x5B: {'location': 'pokemon-tower', 'area': '4f'},
    0x5C: {'location': 'pokemon-tower', 'area': '5f'},
    0x5D: {'location': 'pokemon-tower', 'area': '6f'},
    0x5E: {'location': 'pokemon-tower', 'area': '7f'},
    0x5F: {'location': 'power-plant', 'area': 'whole-area'},
    0x60: {'location': 'mt-ember', 'area': 'ruby-path/b4f'},
    0x61: {'location': 'mt-ember', 'area': 'exterior'},
    0x62: {'location': 'mt-ember', 'area': 'summit-path/1f'},
    0x63: {'location': 'mt-ember', 'area': 'summit-path/2f'},
    0x64: {'location': 'mt-ember', 'area': 'summit-path/3f'},
    0x65: {'location': 'mt-ember', 'area': 'summit'},
    0x66: {'location': 'mt-ember', 'area': 'ruby-path/b5f'},
    0x67: {'location': 'mt-ember', 'area': 'ruby-path/1f'},
    0x68: {'location': 'mt-ember', 'area': 'ruby-path/b1f'},
    0x69: {'location': 'mt-ember', 'area': 'ruby-path/b2f'},
    0x6A: {'location': 'mt-ember', 'area': 'ruby-path/b3f'},
    0x6B: {'location': 'mt-ember', 'area': 'ruby-path/b1f-stairs'},
    0x6C: {'location': 'mt-ember', 'area': 'ruby-path/b2f-stairs'},
    0x6D: {'location': 'three-island', 'area': 'berry-forest'},
    0x6E: {'location': 'four-island', 'area': 'icefall-cave/entrance'},
    0x6F: {'location': 'four-island', 'area': 'icefall-cave/1f'},
    0x70: {'location': 'four-island', 'area': 'icefall-cave/b1f'},
    0x71: {'location': 'four-island', 'area': 'icefall-cave/back'},
    0x72: {'location': 'five-island', 'area': 'rocket-warehouse'},
    0x73: {'location': 'six-island', 'area': 'dotted-hole/1f'},
    0x74: {'location': 'six-island', 'area': 'dotted-hole/b1f'},
    0x75: {'location': 'six-island', 'area': 'dotted-hole/b2f'},
    0x76: {'location': 'six-island', 'area': 'dotted-hole/b3f'},
    0x77: {'location': 'six-island', 'area': 'dotted-hole/b4f'},
    0x78: {'location': 'six-island', 'area': 'dotted-hole/sapphire-room'},
    0x79: {'location': 'six-island', 'area': 'pattern-bush'},
    0x7A: {'location': 'six-island', 'area': 'altering-cave'},
}
map_slugs[0x02] = {
    0x00: {'location': 'navel-rock', 'area': 'exterior'},
    0x01: {'location': 'trainer-tower', 'area': '1f'},
    0x02: {'location': 'trainer-tower', 'area': '2f'},
    0x03: {'location': 'trainer-tower', 'area': '3f'},
    0x04: {'location': 'trainer-tower', 'area': '4f'},
    0x05: {'location': 'trainer-tower', 'area': '5f'},
    0x06: {'location': 'trainer-tower', 'area': '6f'},
    0x07: {'location': 'trainer-tower', 'area': '7f'},
    0x08: {'location': 'trainer-tower', 'area': '8f'},
    0x09: {'location': 'trainer-tower', 'area': 'roof'},
    0x0A: {'location': 'trainer-tower', 'area': 'lobby'},
    0x0B: {'location': 'trainer-tower', 'area': 'elevator'},
    0x0C: {'location': 'five-island', 'area': 'lost-cave/entrance'},
    0x0D: {'location': 'five-island', 'area': 'lost-cave/room-1'},
    0x0E: {'location': 'five-island', 'area': 'lost-cave/room-2'},
    0x0F: {'location': 'five-island', 'area': 'lost-cave/room-3'},
    0x10: {'location': 'five-island', 'area': 'lost-cave/room-4'},
    0x11: {'location': 'five-island', 'area': 'lost-cave/room-5'},
    0x12: {'location': 'five-island', 'area': 'lost-cave/room-6'},
    0x13: {'location': 'five-island', 'area': 'lost-cave/room-7'},
    0x14: {'location': 'five-island', 'area': 'lost-cave/room-8'},
    0x15: {'location': 'five-island', 'area': 'lost-cave/room-9'},
    0x16: {'location': 'five-island', 'area': 'lost-cave/room-10'},
    0x17: {'location': 'five-island', 'area': 'lost-cave/room-11'},
    0x18: {'location': 'five-island', 'area': 'lost-cave/room-12'},
    0x19: {'location': 'five-island', 'area': 'lost-cave/room-13'},
    0x1A: {'location': 'five-island', 'area': 'lost-cave/room-14'},
    0x1B: {'location': 'seven-island', 'area': 'tanoby-ruins/monean-chamber'},
    0x1C: {'location': 'seven-island', 'area': 'tanoby-ruins/liptoo-chamber'},
    0x1D: {'location': 'seven-island', 'area': 'tanoby-ruins/weepth-chamber'},
    0x1E: {'location': 'seven-island', 'area': 'tanoby-ruins/dilford-chamber'},
    0x1F: {'location': 'seven-island', 'area': 'tanoby-ruins/scufib-chamber'},
    0x20: {'location': 'seven-island', 'area': 'tanoby-ruins/rixy-chamber'},
    0x21: {'location': 'seven-island', 'area': 'tanoby-ruins/viapois-chamber'},
    0x22: {'location': 'three-island', 'area': 'dunsparce-tunnel'},
    0x23: {'location': 'seven-island', 'area': 'sevault-canyon/tanoby-key'},
    0x24: {'location': 'navel-rock', 'area': '1f'},
    0x25: {'location': 'navel-rock', 'area': 'summit'},
    0x26: {'location': 'navel-rock', 'area': 'base'},
    0x27: {'location': 'navel-rock', 'area': 'summit-path/2f'},
    0x28: {'location': 'navel-rock', 'area': 'summit-path/3f'},
    0x29: {'location': 'navel-rock', 'area': 'summit-path/4f'},
    0x2A: {'location': 'navel-rock', 'area': 'summit-path/5f'},
    0x2B: {'location': 'navel-rock', 'area': 'base-path/b1f'},
    0x2C: {'location': 'navel-rock', 'area': 'base-path/b2f'},
    0x2D: {'location': 'navel-rock', 'area': 'base-path/b3f'},
    0x2E: {'location': 'navel-rock', 'area': 'base-path/b4f'},
    0x2F: {'location': 'navel-rock', 'area': 'base-path/b5f'},
    0x30: {'location': 'navel-rock', 'area': 'base-path/b6f'},
    0x31: {'location': 'navel-rock', 'area': 'base-path/b7f'},
    0x32: {'location': 'navel-rock', 'area': 'base-path/b8f'},
    0x33: {'location': 'navel-rock', 'area': 'base-path/b9f'},
    0x34: {'location': 'navel-rock', 'area': 'base-path/b10f'},
    0x35: {'location': 'navel-rock', 'area': 'base-path/b11f'},
    0x36: {'location': 'navel-rock', 'area': 'b1f'},
    0x37: {'location': 'navel-rock', 'area': 'fork'},
    0x38: {'location': 'birth-island', 'area': 'exterior'},
    0x39: {'location': 'one-island', 'area': 'kindle-road/ember-spa'},
    0x3A: {'location': 'birth-island', 'area': 'harbor'},
    0x3B: {'location': 'navel-rock', 'area': 'harbor'},
}
map_slugs[0x03] = {
    0x00: {'location': 'pallet-town', 'area': 'whole-area'},
    0x01: {'location': 'viridian-city', 'area': 'whole-area'},
    0x02: {'location': 'pewter-city', 'area': 'whole-area'},
    0x03: {'location': 'cerulean-city', 'area': 'whole-area'},
    0x04: {'location': 'lavender-town', 'area': 'whole-area'},
    0x05: {'location': 'vermilion-city', 'area': 'whole-area'},
    0x06: {'location': 'celadon-city', 'area': 'whole-area'},
    0x07: {'location': 'fuchsia-city', 'area': 'whole-area'},
    0x08: {'location': 'cinnabar-island', 'area': 'whole-area'},
    0x09: {'location': 'indigo-plateau', 'area': 'exterior'},
    0x0A: {'location': 'saffron-city', 'area': 'whole-area'},
    0x0B: {'location': 'saffron-city', 'area': 'connection'},
    0x0C: {'location': 'one-island--town', 'area': 'whole-area'},
    0x0D: {'location': 'two-island--town', 'area': 'whole-area'},
    0x0E: {'location': 'three-island--town', 'area': 'whole-area'},
    0x0F: {'location': 'four-island', 'area': 'whole-area'},
    0x10: {'location': 'five-island--town', 'area': 'whole-area'},
    0x11: {'location': 'seven-island--town', 'area': 'whole-area'},
    0x12: {'location': 'six-island--town', 'area': 'whole-area'},
    0x13: {'location': 'hoenn-route-1', 'area': 'whole-area'},
    0x14: {'location': 'hoenn-route-2', 'area': 'whole-area'},
    0x15: {'location': 'hoenn-route-3', 'area': 'whole-area'},
    0x16: {'location': 'hoenn-route-4', 'area': 'whole-area'},
    0x17: {'location': 'hoenn-route-5', 'area': 'whole-area'},
    0x18: {'location': 'hoenn-route-6', 'area': 'whole-area'},
    0x19: {'location': 'hoenn-route-7', 'area': 'whole-area'},
    0x1A: {'location': 'hoenn-route-8', 'area': 'whole-area'},
    0x1B: {'location': 'hoenn-route-9', 'area': 'whole-area'},
    0x1C: {'location': 'hoenn-route-10', 'area': 'whole-area'},
    0x1D: {'location': 'hoenn-route-11', 'area': 'whole-area'},
    0x1E: {'location': 'hoenn-route-12', 'area': 'whole-area'},
    0x1F: {'location': 'hoenn-route-13', 'area': 'whole-area'},
    0x20: {'location': 'hoenn-route-14', 'area': 'whole-area'},
    0x21: {'location': 'hoenn-route-15', 'area': 'whole-area'},
    0x22: {'location': 'hoenn-route-16', 'area': 'whole-area'},
    0x23: {'location': 'hoenn-route-17', 'area': 'whole-area'},
    0x24: {'location': 'hoenn-route-18', 'area': 'whole-area'},
    0x25: {'location': 'hoenn-route-19', 'area': 'whole-area'},
    0x26: {'location': 'hoenn-route-20', 'area': 'whole-area'},
    0x27: {'location': 'hoenn-route-21', 'area': 'north'},
    0x28: {'location': 'hoenn-route-21', 'area': 'south'},
    0x29: {'location': 'hoenn-route-22', 'area': 'whole-area'},
    0x2A: {'location': 'hoenn-route-23', 'area': 'whole-area'},
    0x2B: {'location': 'hoenn-route-24', 'area': 'whole-area'},
    0x2C: {'location': 'hoenn-route-25', 'area': 'whole-area'},
    0x2D: {'location': 'one-island', 'area': 'kindle-road'},
    0x2E: {'location': 'one-island', 'area': 'treasure-beach'},
    0x2F: {'location': 'two-island', 'area': 'cape-brink'},
    0x30: {'location': 'three-island', 'area': 'bond-bridge'},
    0x31: {'location': 'three-island', 'area': 'port'},
    # 0x32: {'location': 'prototype', 'area': 'sevii-isle/6'},
    # 0x33: {'location': 'prototype', 'area': 'sevii-isle/7'},
    # 0x34: {'location': 'prototype', 'area': 'sevii-isle/8'},
    # 0x35: {'location': 'prototype', 'area': 'sevii-isle/9'},
    0x36: {'location': 'five-island', 'area': 'resort-gorgeous'},
    0x37: {'location': 'five-island', 'area': 'water-labyrinth'},
    0x38: {'location': 'five-island', 'area': 'meadow'},
    0x39: {'location': 'five-island', 'area': 'memorial-pillar'},
    0x3A: {'location': 'six-island', 'area': 'outcast-island'},
    0x3B: {'location': 'six-island', 'area': 'green-path'},
    0x3C: {'location': 'six-island', 'area': 'water-path'},
    0x3D: {'location': 'six-island', 'area': 'ruin-valley'},
    0x3E: {'location': 'seven-island', 'area': 'trainer-tower'},
    0x3F: {'location': 'seven-island', 'area': 'sevault-canyon/entrance'},
    0x40: {'location': 'seven-island', 'area': 'sevault-canyon'},
    0x41: {'location': 'seven-island', 'area': 'tanoby-ruins'},
}
map_slugs[0x04] = {
    0x00: {'location': 'pallet-town', 'area': 'players-house/1f'},
    0x01: {'location': 'pallet-town', 'area': 'players-house/2f'},
    0x02: {'location': 'pallet-town', 'area': 'garys-house'},
    0x03: {'location': 'pallet-town', 'area': 'professor-oaks-lab'},
}
map_slugs[0x05] = {
    0x00: {'location': 'viridian-city', 'area': 'house-1'},
    0x01: {'location': 'viridian-city', 'area': 'gym'},
    0x02: {'location': 'viridian-city', 'area': 'house-2'},
    0x03: {'location': 'viridian-city', 'area': 'mart'},
    0x04: {'location': 'viridian-city', 'area': 'pokemon-center/1f'},
    0x05: {'location': 'viridian-city', 'area': 'pokemon-center/2f'},
}
map_slugs[0x06] = {
    0x00: {'location': 'pewter-city', 'area': 'museum/1f'},
    0x01: {'location': 'pewter-city', 'area': 'museum/2f'},
    0x02: {'location': 'pewter-city', 'area': 'gym'},
    0x03: {'location': 'pewter-city', 'area': 'mart'},
    0x04: {'location': 'pewter-city', 'area': 'house-1'},
    0x05: {'location': 'pewter-city', 'area': 'pokemon-center/1f'},
    0x06: {'location': 'pewter-city', 'area': 'pokemon-center/2f'},
    0x07: {'location': 'pewter-city', 'area': 'house-2'},
}
map_slugs[0x07] = {
    0x00: {'location': 'cerulean-city', 'area': 'house-1'},
    0x01: {'location': 'cerulean-city', 'area': 'house-2'},
    0x02: {'location': 'cerulean-city', 'area': 'house-3'},
    0x03: {'location': 'cerulean-city', 'area': 'pokemon-center/1f'},
    0x04: {'location': 'cerulean-city', 'area': 'pokemon-center/2f'},
    0x05: {'location': 'cerulean-city', 'area': 'gym'},
    0x06: {'location': 'cerulean-city', 'area': 'bike-shop'},
    0x07: {'location': 'cerulean-city', 'area': 'mart'},
    0x08: {'location': 'cerulean-city', 'area': 'house-4'},
    0x09: {'location': 'cerulean-city', 'area': 'house-5'},
}
map_slugs[0x08] = {
    0x00: {'location': 'lavender-town', 'area': 'pokemon-center/1f'},
    0x01: {'location': 'lavender-town', 'area': 'pokemon-center/2f'},
    0x02: {'location': 'lavender-town', 'area': 'volunteer-pokemon-house'},
    0x03: {'location': 'lavender-town', 'area': 'house-1'},
    0x04: {'location': 'lavender-town', 'area': 'house-2'},
    0x05: {'location': 'lavender-town', 'area': 'mart'},
}
map_slugs[0x09] = {
    0x00: {'location': 'vermilion-city', 'area': 'house-1'},
    0x01: {'location': 'vermilion-city', 'area': 'pokemon-center/1f'},
    0x02: {'location': 'vermilion-city', 'area': 'pokemon-center/2f'},
    0x03: {'location': 'vermilion-city', 'area': 'pokemon-fan-club'},
    0x04: {'location': 'vermilion-city', 'area': 'house-2'},
    0x05: {'location': 'vermilion-city', 'area': 'mart'},
    0x06: {'location': 'vermilion-city', 'area': 'gym'},
    0x07: {'location': 'vermilion-city', 'area': 'house-3'},
}
map_slugs[0x0A] = {
    0x00: {'location': 'celadon-city', 'area': 'department-store/1f'},
    0x01: {'location': 'celadon-city', 'area': 'department-store/2f'},
    0x02: {'location': 'celadon-city', 'area': 'department-store/3f'},
    0x03: {'location': 'celadon-city', 'area': 'department-store/4f'},
    0x04: {'location': 'celadon-city', 'area': 'department-store/5f'},
    0x05: {'location': 'celadon-city', 'area': 'department-store/roof'},
    0x06: {'location': 'celadon-city', 'area': 'department-store/elevator'},
    0x07: {'location': 'celadon-city', 'area': 'condominiums/1f'},
    0x08: {'location': 'celadon-city', 'area': 'condominiums/2f'},
    0x09: {'location': 'celadon-city', 'area': 'condominiums/3f'},
    0x0A: {'location': 'celadon-city', 'area': 'condominiums/roof'},
    0x0B: {'location': 'celadon-city', 'area': 'condominiums/roof-room'},
    0x0C: {'location': 'celadon-city', 'area': 'pokemon-center/1f'},
    0x0D: {'location': 'celadon-city', 'area': 'pokemon-center/2f'},
    0x0E: {'location': 'celadon-city', 'area': 'game-corner'},
    0x0F: {'location': 'celadon-city', 'area': 'game-corner/prize-room'},
    0x10: {'location': 'celadon-city', 'area': 'gym'},
    0x11: {'location': 'celadon-city', 'area': 'restaurant'},
    0x12: {'location': 'celadon-city', 'area': 'house-1'},
    0x13: {'location': 'celadon-city', 'area': 'hotel'},
}
map_slugs[0x0B] = {
    0x00: {'location': 'fuchsia-city', 'area': 'safari-zone/entrance'},
    0x01: {'location': 'fuchsia-city', 'area': 'mart'},
    0x02: {'location': 'fuchsia-city', 'area': 'safari-zone/office'},
    0x03: {'location': 'fuchsia-city', 'area': 'gym'},
    0x04: {'location': 'fuchsia-city', 'area': 'house-1'},
    0x05: {'location': 'fuchsia-city', 'area': 'pokemon-center/1f'},
    0x06: {'location': 'fuchsia-city', 'area': 'pokemon-center/2f'},
    0x07: {'location': 'fuchsia-city', 'area': 'wardens-house'},
    0x08: {'location': 'fuchsia-city', 'area': 'house-2'},
    0x09: {'location': 'fuchsia-city', 'area': 'house-3'},
}
map_slugs[0x0C] = {
    0x00: {'location': 'cinnabar-island', 'area': 'gym'},
    0x01: {'location': 'cinnabar-island', 'area': 'pokemon-lab/entrance'},
    0x02: {'location': 'cinnabar-island', 'area': 'pokemon-lab/lounge'},
    0x03: {'location': 'cinnabar-island', 'area': 'pokemon-lab/research-room'},
    0x04: {'location': 'cinnabar-island', 'area': 'pokemon-lab/experiment-room'},
    0x05: {'location': 'cinnabar-island', 'area': 'pokemon-center/1f'},
    0x06: {'location': 'cinnabar-island', 'area': 'pokemon-center/2f'},
    0x07: {'location': 'cinnabar-island', 'area': 'mart'},
}
map_slugs[0x0D] = {
    0x00: {'location': 'indigo-plateau', 'area': 'pokemon-center/1f'},
    0x01: {'location': 'indigo-plateau', 'area': 'pokemon-center/2f'},
}
map_slugs[0x0E] = {
    0x00: {'location': 'saffron-city', 'area': 'copycats-house/1f'},
    0x01: {'location': 'saffron-city', 'area': 'copycats-house/2f'},
    0x02: {'location': 'saffron-city', 'area': 'dojo'},
    0x03: {'location': 'saffron-city', 'area': 'gym'},
    0x04: {'location': 'saffron-city', 'area': 'house'},
    0x05: {'location': 'saffron-city', 'area': 'mart'},
    0x06: {'location': 'saffron-city', 'area': 'pokemon-center/1f'},
    0x07: {'location': 'saffron-city', 'area': 'pokemon-center/2f'},
    0x08: {'location': 'saffron-city', 'area': 'mr-psychics-house'},
    0x09: {'location': 'saffron-city', 'area': 'pokemon-trainer-fan-club'},
}
map_slugs[0x0F] = {
    0x00: {'location': 'hoenn-route-2', 'area': 'viridian-forest/south-entrance'},
    0x01: {'location': 'hoenn-route-2', 'area': 'house'},
    0x02: {'location': 'hoenn-route-2', 'area': 'east-building'},
    0x03: {'location': 'hoenn-route-2', 'area': 'viridian-forest/north-entrance'},
}
map_slugs[0x10] = {
    0x00: {'location': 'hoenn-route-4', 'area': 'pokemon-center/1f'},
    0x01: {'location': 'hoenn-route-4', 'area': 'pokemon-center/2f'},
}
map_slugs[0x11] = {
    0x00: {'location': 'hoenn-route-5', 'area': 'pokemon-day-care'},
    0x01: {'location': 'hoenn-route-5', 'area': 'south-entrance'},
}
map_slugs[0x12] = {
    0x00: {'location': 'hoenn-route-6', 'area': 'north-entrance'},
    # 0x01: {'location': 'unknown-map', 'area': '18/01'},
}
map_slugs[0x13] = {
    0x00: {'location': 'hoenn-route-7', 'area': 'east-entrance'},
}
map_slugs[0x14] = {
    0x00: {'location': 'hoenn-route-8', 'area': 'west-entrance'},
}
map_slugs[0x15] = {
    0x00: {'location': 'hoenn-route-10', 'area': 'pokemon-center/1f'},
    0x01: {'location': 'hoenn-route-10', 'area': 'pokemon-center/2f'},
}
map_slugs[0x16] = {
    0x00: {'location': 'hoenn-route-11', 'area': 'east-entrance/1f'},
    0x01: {'location': 'hoenn-route-11', 'area': 'east-entrance/2f'},
}
map_slugs[0x17] = {
    0x00: {'location': 'hoenn-route-12', 'area': 'north-entrance/1f'},
    0x01: {'location': 'hoenn-route-12', 'area': 'north-entrance/2f'},
    0x02: {'location': 'hoenn-route-12', 'area': 'fishing-house'},
}
map_slugs[0x18] = {
    0x00: {'location': 'hoenn-route-15', 'area': 'west-entrance/1f'},
    0x01: {'location': 'hoenn-route-15', 'area': 'west-entrance/2f'},
}
map_slugs[0x19] = {
    0x00: {'location': 'hoenn-route-16', 'area': 'house'},
    0x01: {'location': 'hoenn-route-16', 'area': 'north-entrance/1f'},
    0x02: {'location': 'hoenn-route-16', 'area': 'north-entrance/2f'},
}
map_slugs[0x1A] = {
    0x00: {'location': 'hoenn-route-18', 'area': 'east-entrance/1f'},
    0x01: {'location': 'hoenn-route-18', 'area': 'east-entrance/2f'},
}
map_slugs[0x1B] = {
    # 0x00: {'location': 'unused-house', 'area': '27/00'},
}
map_slugs[0x1C] = {
    0x00: {'location': 'hoenn-route-22', 'area': 'north-entrance'},
}
map_slugs[0x1D] = {
    # 0x00: {'location': 'unused-house', 'area': '29/00'},
}
map_slugs[0x1E] = {
    0x00: {'location': 'hoenn-route-25', 'area': 'sea-cottage'},
}
map_slugs[0x1F] = {
    0x00: {'location': 'seven-island', 'area': 'house/room-1'},
    0x01: {'location': 'seven-island', 'area': 'house/room-2'},
    0x02: {'location': 'seven-island', 'area': 'mart'},
    0x03: {'location': 'seven-island', 'area': 'pokemon-center/1f'},
    0x04: {'location': 'seven-island', 'area': 'pokemon-center/2f'},
    # 0x05: {'location': 'unused-house', 'area': '31/05'},
    0x06: {'location': 'seven-island', 'area': 'harbor'},
}
map_slugs[0x20] = {
    0x00: {'location': 'one-island', 'area': 'pokemon-center/1f'},
    0x01: {'location': 'one-island', 'area': 'pokemon-center/2f'},
    0x02: {'location': 'one-island', 'area': 'house-1'},
    0x03: {'location': 'one-island', 'area': 'house-2'},
    0x04: {'location': 'one-island', 'area': 'harbor'},
}
map_slugs[0x21] = {
    0x00: {'location': 'two-island', 'area': 'joyful-game-corner'},
    0x01: {'location': 'two-island', 'area': 'house'},
    0x02: {'location': 'two-island', 'area': 'pokemon-center/1f'},
    0x03: {'location': 'two-island', 'area': 'pokemon-center/2f'},
    0x04: {'location': 'two-island', 'area': 'harbor'},
}
map_slugs[0x22] = {
    0x00: {'location': 'three-island', 'area': 'house-1'},
    0x01: {'location': 'three-island', 'area': 'pokemon-center/1f'},
    0x02: {'location': 'three-island', 'area': 'pokemon-center/2f'},
    0x03: {'location': 'three-island', 'area': 'mart'},
    0x04: {'location': 'three-island', 'area': 'house-2'},
    0x05: {'location': 'three-island', 'area': 'house-3'},
    0x06: {'location': 'three-island', 'area': 'house-4'},
    0x07: {'location': 'three-island', 'area': 'house-5'},
}
map_slugs[0x23] = {
    0x00: {'location': 'four-island', 'area': 'pokemon-day-care'},
    0x01: {'location': 'four-island', 'area': 'pokemon-center/1f'},
    0x02: {'location': 'four-island', 'area': 'pokemon-center/2f'},
    0x03: {'location': 'four-island', 'area': 'house-1'},
    0x04: {'location': 'four-island', 'area': 'loreleis-house'},
    0x05: {'location': 'four-island', 'area': 'harbor'},
    0x06: {'location': 'four-island', 'area': 'house-2'},
    0x07: {'location': 'four-island', 'area': 'mart'},
}
map_slugs[0x24] = {
    0x00: {'location': 'five-island', 'area': 'pokemon-center/1f'},
    0x01: {'location': 'five-island', 'area': 'pokemon-center/2f'},
    0x02: {'location': 'five-island', 'area': 'harbor'},
    0x03: {'location': 'five-island', 'area': 'house-1'},
    0x04: {'location': 'five-island', 'area': 'house-2'},
}
map_slugs[0x25] = {
    0x00: {'location': 'six-island', 'area': 'pokemon-center/1f'},
    0x01: {'location': 'six-island', 'area': 'pokemon-center/2f'},
    0x02: {'location': 'six-island', 'area': 'harbor'},
    0x03: {'location': 'six-island', 'area': 'house'},
    0x04: {'location': 'six-island', 'area': 'mart'},
}
map_slugs[0x26] = {
    0x00: {'location': 'three-island', 'area': 'harbor'},
}
map_slugs[0x27] = {
    0x00: {'location': 'five-island', 'area': 'resort-gorgeous/house'},
}
map_slugs[0x28] = {
    0x00: {'location': 'two-island', 'area': 'cape-brink/house'},
}
map_slugs[0x29] = {
    0x00: {'location': 'six-island', 'area': 'water-path/house-1'},
    0x01: {'location': 'six-island', 'area': 'water-path/house-2'},
}
map_slugs[0x2A] = {
    0x00: {'location': 'seven-island', 'area': 'sevault-canyon/house'},
}
