apiVersion: batch/v1
kind: Job
metadata:
  name: load-data
spec:
  template:
    spec:
      containers:
        - name: load-data
          image: ${IMAGE_BASENAME}/data:${BUILD_NUMBER}
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: database.host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: database.port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: database.user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: database.password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: database.db
      restartPolicy: Never
  backoffLimit: 4
