apiVersion: batch/v1
kind: Job
metadata:
  name: searchseed
  namespace: poketools
spec:
  template:
    spec:
      initContainers:
        - name: wait-elasticsearch
          image: busybox
          command: ['sh', '-c', 'until nc -vz elasticsearch-service 9200; do echo waiting for elasticsearch-service; sleep 2; done;']
        - name: wait-db
          image: busybox
          command: ['sh', '-c', 'until nc -vz db-service 5432; do echo waiting for db-service; sleep 30; done;']
      containers:
        - env:
            - name: APP_VERSION
              value: ${APP_VERSION}
            - name: BUILD_NUMBER
              value: ${BUILD_NUMBER}
            - name: APP_ENV
              value: prod
            - name: APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: app.secret
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: database.url
            - name: MAILER_URL
              valueFrom:
                secretKeyRef:
                  name: poketools-secret
                  key: mailer.url
            - name: ELASTICA_CLIENT_HOST
              value: elasticsearch-service
          image: ${IMAGE_BASENAME}/app:${BUILD_NUMBER}
          name: php
          command: ["/bin/sh","-c"]
          args:
            - |
              php -d memory_limit=256M bin/console cache:clear &&
              bin/console assets:install &&
              chown -R www-data:www-data var &&
              php -d memory_limit=256M bin/console fos:elastica:populate --no-interaction --no-ansi --no-debug
      restartPolicy: Never
  backoffLimit: 4
