a2b:
  sources:
    - name: veekun
      uri: "sqlite:///%kernel.project_dir%/resources/pokedex/pokedex/data/pokedex.sqlite"
  destinations:
    - name: pokemon_move
      uri: "%env(resolve:DATABASE_URL)%#pokemon_move"
