# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/Resources/doc/setup.md
fos_elastica:
  clients:
    default:
      host: '%env(ELASTICA_CLIENT_HOST)%'
      port: 9200
  indexes:
    #    generation:
    #      types:
    #        generation:
    #          persistence:
    #            driver: orm
    #            model: App\Entity\Generation
    #            listener:
    #              enabled: false
    #          properties:
    #            id: ~
    #            name: ~
    #            version_groups:
    #              type: nested
    #              property_path: versionGroups
    #              properties:
    #                id: ~
    #                name: ~
    #                versions:
    #                  type: nested
    #                  properties:
    #                    id: ~
    #                    name: ~
    #
    #    version_group:
    #      types:
    #        version_group:
    #          persistence:
    #            driver: orm
    #            model: App\Entity\VersionGroup
    #            listener:
    #              enabled: false
    #          properties:
    #            id: ~
    #            name: ~
    #            generation:
    #              type: object
    #              properties:
    #                id: ~
    #                name: ~
    #            versions:
    #              type: nested
    #              properties:
    #                id: ~
    #                name: ~
    #
    #    version:
    #      types:
    #        version:
    #          persistence:
    #            driver: orm
    #            model: App\Entity\Version
    #            listener:
    #              enabled: false
    #          properties:
    #            id: ~
    #            name: ~
    #            version_group:
    #              type: object
    #              property_path: versionGroup
    #              properties:
    #                id: ~
    #                name: ~
    #                generation:
    #                  type: object
    #                  properties:
    #                    id: ~
    #                    name: ~
    
    pokemon:
      types:
        pokemon:
          persistence:
            driver: orm
            model: App\Entity\Pokemon
            listener:
              enabled: false
          properties:
            id: ~
            name:
            version_group:
              type: object
              property_path: species.versionGroup
              properties:
                id: ~
                name: ~
            evolution_family:
              type: nested
              property_path: evolutionFamily
              properties:
                id: ~
                name: ~
            color:
              type: object
              properties:
                id: ~
                name: ~
            shape:
              type: object
              properties:
                id: ~
                name: ~
            habitat:
              type: object
              properties:
                id: ~
                name: ~
            growth_rate:
              type: object
              properties:
                name: ~
            genus: ~
            flavor_text:
              type: nested
              property_path: flavorText
              properties:
                version:
                  type: object
                  properties:
                    id: ~
                    name: ~
                flavor_text:
                  property_path: flavorText
            egg_groups:
              type: nested
              property_path: eggGroups
              properties:
                id: ~
                name: ~
            abilities:
              type: nested
              property_path: abilities
              properties:
                id:
                  property_path: ability.id
                name:
                  property_path: ability.name
                hidden:
            wild_held_items:
              type: nested
              property_path: wildHeldItems
              properties:
                id:
                  property_path: item.id
                version:
                  type: object
                  properties:
                    id: ~
                    name: ~
                name:
                  property_path: item.name
                rate: ~
            types:
              type: nested
              properties:
                id:
                  property_path: type.id
                name:
                  property_path: type.name
            forms:
              type: nested
              properties:
                id: ~
                name: ~
    move:
      types:
        move:
          persistence:
            driver: orm
            model: App\Entity\MoveInVersionGroup
            listener:
              enabled: false
          properties:
            id: ~
            name: ~
            version_group:
              type: object
              property_path: versionGroup
              properties:
                id: ~
                name: ~
            description: ~
            type:
              type: object
              properties:
                id: ~
                name: ~
            flavor_text:
              property_path: flavorText
            effect:
              property_path: effect.description
            categories:
              type: nested
              properties:
                id: ~
                name: ~
                description: ~
            machine:
              type: object
              properties:
                name:
                  property_path: item.name
                move:
                  property_path: move.name
            flags:
              type: nested
              properties:
                name: ~
                description: ~
    
    type:
      types:
        type:
          persistence:
            driver: orm
            model: App\Entity\Type
            listener:
              enabled: false
          properties:
            id: ~
            name: ~
            damage_class:
              type: object
              property_path: damageClass
              properties:
                id: ~
                name: ~
    
    item:
      types:
        item:
          persistence:
            driver: orm
            model: App\Entity\ItemInVersionGroup
            listener:
              enabled: false
          properties:
            id: ~
            name: ~
            version_group:
              type: object
              property_path: versionGroup
              properties:
                id: ~
                name: ~
            description: ~
            flavor_text:
              property_path: flavorText
            categories:
              type: nested
              property_path: category.fullTree
              properties:
                id: ~
                name: ~
            pocket:
              type: object
              properties:
                id: ~
                name: ~
            flags:
              type: nested
              properties:
                id: ~
                name: ~
                description: ~
    
    location:
      types:
        location:
          persistence:
            driver: orm
            model: App\Entity\LocationInVersionGroup
            listener:
              enabled: false
          properties:
            id: ~
            name: ~
            version_group:
              type: object
              property_path: versionGroup
              properties:
                id: ~
                name: ~
            description: ~
            region:
              type: object
              properties:
                id: ~
                name: ~
            areas:
              type: nested
              properties:
                id: ~
                name: ~
    
    nature:
      types:
        nature:
          persistence:
            driver: orm
            model: App\Entity\Nature
            listener:
              enabled: false
          properties:
            id: ~
            name: ~
            stat_increased:
              type: object
              property_path: statIncreased
              properties:
                id: ~
                name: ~
            stat_decreased:
              type: object
              property_path: statDecreased
              properties:
                id: ~
                name: ~
            flavor_likes:
              type: object
              property_path: flavorLikes
              properties:
                id: ~
                name: ~
            flavor_hates:
              type: object
              property_path: flavorHates
              properties:
                id: ~
                name: ~
    
    ability:
      types:
        ability:
          persistence:
            driver: orm
            model: App\Entity\AbilityInVersionGroup
            listener:
              enabled: false
          properties:
            id: ~
            name: ~
            version_group:
              type: object
              property_path: versionGroup
              properties:
                id: ~
                name: ~
            description: ~
            flavor_text:
              property_path: flavorText
