twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  paths:
    '%kernel.project_dir%/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views': ~
  globals:
    app_name: '%app_name%'
    default_version: '%default_version%'
