twig:
  default_path: '%kernel.project_dir%/templates'
  debug: '%kernel.debug%'
  auto_reload: '%kernel.debug%'
  strict_variables: '%kernel.debug%'
  form_themes:
    - 'bootstrap_4_horizontal_layout.html.twig'
  paths:
    '%kernel.project_dir%/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views': ~
  globals:
    app_name: '%app_name%'
    app_version: '%env(APP_VERSION)%'
    default_version: '%default_version%'
