# the different stages of this Dockerfile are meant to be built into separate images
# https://docs.docker.com/compose/compose-file/#target

ARG PHP_VERSION=7.2
ARG NGINX_VERSION=1.15
ARG VARNISH_VERSION=6.0

FROM php:${PHP_VERSION}-fpm-alpine AS api_platform_php

# persistent / runtime deps
RUN apk add --no-cache \
		acl \
		file \
		gettext \
		git \
		postgresql-client \
	;

ARG APCU_VERSION=5.1.11
ARG XDEBUG_VERSION
RUN set -eux; \
	apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		icu-dev \
		libzip-dev \
		postgresql-dev \
		zlib-dev \
	; \
	\
	docker-php-ext-configure zip --with-libzip; \
	docker-php-ext-install -j$(nproc) \
		intl \
		pdo_pgsql \
		zip \
	; \
	pecl install \
		apcu-${APCU_VERSION} \
		xdebug \
	; \
	pecl clear-cache; \
	docker-php-ext-enable \
		apcu \
		opcache \
		xdebug \
	; \
	\
	runDeps="$( \
		scanelf --needed --nobanner --format '%n#p' --recursive /usr/local/lib/php/extensions \
			| tr ',' '\n' \
			| sort -u \
			| awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
	)"; \
	apk add --no-cache --virtual .api-phpexts-rundeps $runDeps; \
	\
	apk del .build-deps

COPY docker/php/php.ini /usr/local/etc/php/php.ini

ARG XDEBUG_REMOTE_HOST
RUN XDEBUG_PATH=$(find /usr/local/lib/php/extensions/ -name xdebug.so); \
    if [ -n "$XDEBUG_PATH" ]; then \
        echo "xdebug.remote_host=\"${XDEBUG_REMOTE_HOST}\"" > /usr/local/etc/php/conf.d/xdebug.ini; \
    fi

# Install composer inside the PHP container
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
#COPY docker/php/get-composer.sh /tmp/get-composer.sh
#RUN chmod +x /tmp/get-composer.sh; \
#    /bin/sh /tmp/get-composer.sh; \
#    mv composer.phar /usr/local/bin/composer

# build for development
COPY . /srv/api
WORKDIR /srv/api
ARG APP_ENV=dev
VOLUME /srv/api/var
ENV COMPOSER_ALLOW_SUPERUSER=1
RUN set -eux; \
    composer install --no-progress
COPY docker/php/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
RUN chmod +x /usr/local/bin/docker-entrypoint

ENTRYPOINT ["docker-entrypoint"]
CMD ["php-fpm"]

FROM nginx:${NGINX_VERSION}-alpine AS api_platform_nginx

COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

WORKDIR /srv/api

COPY --from=api_platform_php /srv/api/public public/

FROM cooptilleuls/varnish:${VARNISH_VERSION}-alpine AS api_platform_varnish

COPY docker/varnish/conf/default.vcl /usr/local/etc/varnish/default.vcl
